import {test,expect} from '@playwright/test';
import path from 'node:path';
test('workspace → brand → CSV mapping → evidence → draft version → export; persistence and isolation',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByRole('heading',{name:'A little clarity. A better next move.'})).toBeVisible();
 await expect(page.getByText('4 supported opportunities, ready for your review.')).toBeVisible();
 await page.screenshot({path:'docs/desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Set up your workspace'}).click();
 await page.getByRole('button',{name:'Your local sandbox'}).click();
 const onboard=page.getByRole('dialog');await expect(onboard).toBeVisible();
 await onboard.getByLabel('Business name').fill('Northstar Studio');await onboard.getByLabel('Website',{exact:true}).fill('https://example.com');
 await onboard.getByLabel('Products or services').fill('Marketing operations consulting');
 await onboard.getByLabel('Target audience').fill('B2B software teams');
 await onboard.getByRole('button',{name:'Save approved business profile'}).click();
 await expect(onboard).not.toBeVisible();
 await expect(page.getByRole('heading',{name:'No supported opportunities found'})).toBeVisible();
 await page.getByRole('button',{name:'Import data',exact:true}).click();
 const importer=page.getByRole('dialog');await importer.getByLabel('Source account / property ID').fill('properties/1234');
 await importer.getByLabel('CSV file').setInputFiles(path.resolve('public/samples/ga4.csv'));
 await importer.getByRole('button',{name:'Validate & preview'}).click();
 await expect(importer.getByRole('heading',{name:'56 valid daily records'})).toBeVisible();
 await importer.getByRole('button',{name:'Import & find opportunities'}).click();
 await expect(importer.getByRole('button',{name:'Imported successfully'})).toBeVisible();
 await importer.getByRole('button',{name:'Close dialog'}).click();
 await expect(page.getByRole('heading',{name:'Conversion rate fell on /book-a-demo'})).toBeVisible();
 await page.getByRole('button',{name:'Review opportunity'}).click();
 const evidence=page.getByRole('dialog');await evidence.getByText('Inspect 14 supporting daily records').click();
 await expect(evidence.getByRole('columnheader',{name:'Sessions',exact:true})).toBeVisible();
 await evidence.getByRole('button',{name:'Prepare draft / checklist'}).click();
 const editor=page.getByRole('dialog');const input=editor.getByLabel('Draft content');await expect(input).toBeVisible();
 await input.fill((await input.inputValue())+'\n\nUpdated CTA: Talk to our team');
 await editor.getByLabel('Version notes / feedback').fill('Make the next step clearer');
 await editor.getByRole('button',{name:'Save new version'}).click();
 await expect(editor.getByText('Version 2 · Needs review',{exact:true})).toBeVisible();
 const downloadPromise=page.waitForEvent('download');await editor.getByRole('button',{name:'Download',exact:true}).click();const file=await downloadPromise;expect(file.suggestedFilename()).toBe('growthos-draft-v2.md');
 await editor.getByRole('button',{name:'Mark version reviewed'}).click();await expect(editor.getByText('Version 2 · Reviewed',{exact:true})).toBeVisible();
 await editor.getByRole('button',{name:'Close dialog'}).click();
 await page.reload();await expect(page.getByText('LOCAL SANDBOX',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Set up your workspace'}).click();await page.getByRole('button',{name:'Explore the Forma demo'}).click();await expect(page.getByText('4 supported opportunities, ready for your review.')).toBeVisible();
 await page.getByRole('button',{name:'Set up your workspace'}).click();await page.getByRole('button',{name:'Your local sandbox'}).click();
 await expect(page.getByRole('heading',{name:'Conversion rate fell on /book-a-demo'})).toBeVisible();
 await page.getByRole('button',{name:'Drafts',exact:true}).click();await page.getByRole('button',{name:/A more focused first impression/}).click();
 await expect(page.getByLabel('Draft content')).toHaveValue(/Updated CTA: Talk to our team/);
 expect(errors).toEqual([]);
});
test('mobile navigation, dialogs and layout are usable',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.getByRole('heading',{name:'A little clarity. A better next move.'})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'docs/mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('button',{name:'Connections',exact:true}).click();await expect(page.getByRole('heading',{name:'Good decisions start here.'})).toBeVisible();
 await page.getByRole('button',{name:'Import CSV',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();
});
