import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {companyApi,authorize} from '../server/company.mjs';
import {zapierApi} from '../server/zapier.mjs';
import {api as googleApi} from '../server/index.mjs';
import {save,load} from '../server/security.mjs';
import {emptyWorkspace} from '../lib/domain/types';
const origin='https://example.chatgpt.site';
function setup(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../drizzle/0000_melodic_mister_sinister.sql',import.meta.url),'utf8'));db.exec(readFileSync(new URL('../drizzle/0001_elite_gressill.sql',import.meta.url),'utf8'));const map=new Map<string,{value:string;etag:string}>();let serial=0;return {COMPANY_ID:'company-a',GOOGLE_OWNER_EMAIL:'owner@example.com',GOOGLE_APP_ORIGIN:origin,GOOGLE_CLIENT_ID:'test',GOOGLE_CLIENT_SECRET:'test',CONNECTION_ENCRYPTION_KEY:'ab'.repeat(32),DB:{prepare:(sql:string)=>({bind:(...args:any[])=>({first:async()=>db.prepare(sql).get(...args)??null,all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>db.prepare(sql).run(...args)})}),batch:async(statements:any[])=>{db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}},BUCKET:{get:async(k:string)=>{const o=map.get(k);return o?{etag:o.etag,text:async()=>o.value}:null;},put:async(k:string,value:string,options:any={})=>{const current=map.get(k);if(options.onlyIf?.etagMatches&&options.onlyIf.etagMatches!==current?.etag)return null;if(options.onlyIf?.etagDoesNotMatch==='*'&&current)return null;const o={value,etag:String(++serial)};map.set(k,o);return o;},delete:async(k:string)=>{map.delete(k);}},db,map};}
function request(path:string,email='owner@example.com',body?:unknown){return new Request(origin+path,{method:body?'POST':'GET',headers:{'oai-authenticated-user-id':'user:'+email,'oai-authenticated-user-email':email,origin,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});}
async function add(e:any,email:string,role='member'){assert.equal((await companyApi(request('/api/company/team','owner@example.com',{email,role}),e)).status,200);}
test('company membership enforces roles, immutable owner, removal and isolation',async()=>{const e=setup();assert.equal((await companyApi(request('/api/company/me','stranger@example.com'),e)).status,403);await add(e,'member@example.com');await add(e,'admin@example.com','admin');assert.equal((await authorize(request('/api/company/me','member@example.com'),e)).canAdmin,false);assert.equal((await companyApi(request('/api/company/team','member@example.com',{email:'hacker@example.com',role:'admin'}),e)).status,403);assert.equal((await companyApi(request('/api/company/team','admin@example.com',{email:'owner@example.com',remove:true}),e)).status,400);assert.equal((await companyApi(request('/api/company/me','member@example.com'),{...e,COMPANY_ID:'company-b'})).status,403);await companyApi(request('/api/company/team','admin@example.com',{email:'member@example.com',remove:true}),e);assert.equal((await companyApi(request('/api/company/me','member@example.com'),e)).status,403);e.db.close();});
test('members see company reports but cannot configure, disconnect or authorize credentials',async()=>{const e=setup();await add(e,'member@example.com');await save(e,'company:company-a','zapier',{token:'never-expose-this-secret'});await save(e,'company:company-a','zapier-ga4',{rows:[['shared']]},'report');const status=await (await zapierApi(request('/api/zapier/status','member@example.com'),e)).text();assert(!status.includes('never-expose'));assert(status.includes('shared'));assert.equal(JSON.parse(status).canAdmin,false);for(const path of ['configure','disconnect'])assert.equal((await zapierApi(request('/api/zapier/'+path,'member@example.com',{token:'attacker-token-long-value'}),e)).status,403);for(const path of ['oauth/start','disconnect','sync'])assert.equal((await googleApi(request('/api/google/'+path+'?source=ga4','member@example.com',{source:'ga4'}),e)).status,403);assert.equal((await load(e,'company:company-a','zapier')).token,'never-expose-this-secret');assert.equal((await (await zapierApi(request('/api/zapier/status'),{...e,COMPANY_ID:'company-b'})).json()).configured,false);e.db.close();});
test('shared workspace is durable, rejects stale writes and keeps company boundaries',async()=>{const e=setup();await add(e,'member@example.com');const state={...emptyWorkspace('company'),id:'company-a',revision:-1,profile:{...emptyWorkspace().profile,name:'Company'}};assert.equal((await companyApi(request('/api/company/workspace','member@example.com',{workspace:state,expectedRevision:-1}),e)).status,403);const created=await (await companyApi(request('/api/company/workspace','owner@example.com',{workspace:state,expectedRevision:-1}),e)).json();assert.equal(created.workspace.revision,0);const memberRead=await (await companyApi(request('/api/company/workspace','member@example.com'),e)).json();assert.equal(memberRead.workspace.profile.name,'Company');const updated={...memberRead.workspace,decisions:[{id:'decision',reason:'Reviewed by teammate'}]};assert.equal((await companyApi(request('/api/company/workspace','member@example.com',{workspace:updated,expectedRevision:0}),e)).status,200);assert.equal((await companyApi(request('/api/company/workspace','owner@example.com',{workspace:created.workspace,expectedRevision:0}),e)).status,409);const other=await (await companyApi(request('/api/company/workspace'),{...e,COMPANY_ID:'company-b'})).json();assert.equal(other.workspace,null);e.db.close();});
test('owner migration preserves data without leaving old tokens or copying it again',async()=>{const e=setup(),old='user:owner@example.com';await save(e,old,'zapier',{token:'original-token'});assert.equal((await companyApi(request('/api/company/migrate','owner@example.com',{}),e)).status,200);assert.equal((await load(e,'company:company-a','zapier')).token,'original-token');assert.equal(await load(e,old,'zapier'),null);await zapierApi(request('/api/zapier/disconnect','owner@example.com',{}),e);await companyApi(request('/api/company/migrate','owner@example.com',{}),e);assert.equal(await load(e,'company:company-a','zapier'),null);e.db.close();});

test('brands preserve the first workspace and keep reports, credentials and writes separate',async()=>{
 const e=setup();await add(e,'member@example.com');
 await save(e,'company:company-a','zapier',{token:'original-private-token'});
 await save(e,'company:company-a','zapier-ga4',{rows:[['Primary report']]},'report');
 const first=await (await companyApi(request('/api/company/brands'),e)).json();assert.equal(first.brands.length,1);assert.equal(first.brands[0].id,'company-a');
 assert.equal((await companyApi(request('/api/company/brands','member@example.com',{name:'Beta',website:'https://beta.example'}),e)).status,403);
 assert.equal((await companyApi(request('/api/company/brands','owner@example.com',{name:'Bad',website:'javascript:alert(1)'}),e)).status,400);
 const created=await (await companyApi(request('/api/company/brands','owner@example.com',{name:'Beta',website:'https://beta.example'}),e)).json();const id=created.brand.id,query='?brand='+id;
 assert.equal((await (await companyApi(request('/api/company/brands'),e)).json()).brands.length,2);
 const blank=await (await zapierApi(request('/api/zapier/status'+query),e)).json();assert.equal(blank.configured,false);assert.deepEqual(blank.settings,{});assert.equal(blank.reports.ga4,null);
 assert.equal((await (await googleApi(request('/api/google/status'+query),e)).json()).connections.ga4,null);
 const state={...emptyWorkspace('company'),id,revision:-1,profile:{...emptyWorkspace().profile,name:'Beta',website:'https://beta.example'},decisions:[{id:'beta-decision'}]};
 assert.equal((await companyApi(request('/api/company/workspace'+query,'owner@example.com',{workspace:state,expectedRevision:-1}),e)).status,200);
 assert.equal((await (await companyApi(request('/api/company/workspace'+query,'member@example.com'),e)).json()).workspace.decisions[0].id,'beta-decision');
 assert.equal((await (await companyApi(request('/api/company/workspace'),e)).json()).workspace,null);
 assert.equal((await companyApi(request('/api/company/workspace'+query,'owner@example.com',{workspace:{...state,id:'company-a'},expectedRevision:0}),e)).status,400);
 assert.equal((await companyApi(request('/api/company/workspace'+query,'owner@example.com',{workspace:state,expectedRevision:-1}),e)).status,409);
 assert.equal((await zapierApi(request('/api/zapier/status'+query),{...e,COMPANY_ID:'company-b'})).status,404);
 assert.equal((await googleApi(request('/api/google/status?brand=unknown'),e)).status,404);
 assert.equal((await zapierApi(request('/api/zapier/disconnect'+query,'owner@example.com',{}),e)).status,200);
 assert.equal((await load(e,'company:company-a','zapier')).token,'original-private-token');
 assert.deepEqual((await load(e,'company:company-a','zapier-ga4','report')).rows,[['Primary report']]);e.db.close();
});
test('OAuth state carries the selected brand and callback writes only to that brand',async()=>{
 const e=setup();const {brand}=await (await companyApi(request('/api/company/brands','owner@example.com',{name:'OAuth brand',website:'https://oauth.example'}),e)).json();
 const start=await googleApi(new Request(origin+'/api/google/oauth/start?brand='+brand.id,{method:'POST',headers:{origin,'oai-authenticated-user-id':'user:owner@example.com','oai-authenticated-user-email':'owner@example.com'},body:new URLSearchParams({source:'ga4'})}),e);
 assert.equal(start.status,303);const auth=new URL(start.headers.get('location')!);const nonce=auth.searchParams.get('state');const cookie=start.headers.get('set-cookie')!.split(';')[0];
 const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({access_token:'new-private-access',refresh_token:'new-private-refresh',expires_in:3600,scope:'https://www.googleapis.com/auth/analytics.readonly'}));
 try{const callback=await googleApi(new Request(origin+'/api/google/oauth/callback?state='+nonce+'&code=test',{headers:{cookie,'oai-authenticated-user-id':'user:owner@example.com','oai-authenticated-user-email':'owner@example.com'}}),e);assert.equal(callback.status,303);assert(callback.headers.get('location')!.includes('brand='+brand.id));assert.equal(await load(e,'company:company-a','ga4'),null);assert.equal((await load(e,'company:company-a:brand:'+brand.id,'ga4')).refreshToken,'new-private-refresh');}finally{globalThis.fetch=original;e.db.close();}
});

test('performance history is brand scoped, credentials stay private, and disconnect clears history',async()=>{
 const {performanceApi}=await import('../server/performance.mjs');const e=setup();await add(e,'member@example.com');await save(e,'company:company-a','zapier',{token:'secret-performance-token'});await save(e,'company:company-a','performance-paid',{start:'2020-01-01',end:'2099-12-31',rows:[{name:'Owner brand report'}]},'report');
 assert.equal((await performanceApi(request('/api/performance/status','stranger@example.com'),e)).status,403);
 const status=await (await performanceApi(request('/api/performance/status','member@example.com'),e)).text();assert(status.includes('Owner brand report'));assert(!status.includes('secret-performance-token'));
 const {brand}=await (await companyApi(request('/api/company/brands','owner@example.com',{name:'Separate brand',website:'https://separate.example'}),e)).json();const separate=await (await performanceApi(request('/api/performance/status?brand='+brand.id),e)).json();assert.equal(separate.configured,false);assert.equal(separate.reports.paid,null);assert.equal((await performanceApi(request('/api/performance/status?brand=unknown'),e)).status,404);
 await save(e,'company:company-a','performance-paid',{at:new Date().toISOString()},'attempt');const cached=await (await performanceApi(request('/api/performance/sync','member@example.com',{kind:'paid',force:true}),e)).json();assert.equal(cached.cached,true);assert.equal(cached.report.rows[0].name,'Owner brand report');
 await zapierApi(request('/api/zapier/disconnect','owner@example.com',{}),e);assert.equal(await load(e,'company:company-a','performance-paid','report'),null);e.db.close();
});
