import {test} from 'node:test';
import assert from 'node:assert/strict';
import {api,createWorker} from '../server/index.mjs';
import {seal,unseal,save,load,scopes} from '../server/security.mjs';
import {report,dates} from '../server/providers.mjs';
const origin='https://example.chatgpt.site';
function env(){const map=new Map();return {COMPANY_ID:'test-company',DB:{prepare:()=>({bind:()=>({first:async()=>null})})},GOOGLE_APP_ORIGIN:origin,GOOGLE_OWNER_EMAIL:'owner@example.com',GOOGLE_CLIENT_ID:'test',GOOGLE_CLIENT_SECRET:'test',CONNECTION_ENCRYPTION_KEY:'ab'.repeat(32),BUCKET:{get:async(k:string)=>map.has(k)?{text:async()=>map.get(k)}:null,put:async(k:string,v:string)=>{map.set(k,v);},delete:async(k:string)=>{map.delete(k);}},map};}
function req(path:string,init:RequestInit={}){return new Request(origin+path,{...init,headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.com',...init.headers}});}
test('Google routes reject unauthenticated and nonowner requests',async()=>{const e=env();assert.equal((await api(new Request(origin+'/api/google/status'),e)).status,401);assert.equal((await api(req('/api/google/status',{headers:{'oai-authenticated-user-email':'other@example.com'}}),e)).status,403);});
test('credentials are encrypted, user-bound and absent from status',async()=>{const e=env();await save(e,'company:test-company','ga4',{refreshToken:'private-refresh',accessToken:'private-access',connectedAt:'now'});assert.equal((await load(e,'company:test-company','ga4')).refreshToken,'private-refresh');assert.equal(await load(e,'other','ga4'),null);assert(![...e.map.values()][0].includes('private-refresh'));const status=await (await api(req('/api/google/status'),e)).text();assert(!status.includes('private-'));assert(status.includes('authorized'));const blob=await seal(e,{test:1},'a');await assert.rejects(unseal(e,blob,'b'));});
test('OAuth start binds owner, expiry, state and PKCE; cross-origin POST fails',async()=>{const e=env();const body=()=>new URLSearchParams({source:'ga4'});assert.equal((await api(req('/api/google/oauth/start',{method:'POST',body:body(),headers:{origin:'https://evil.example'}}),e)).status,400);const r=await api(req('/api/google/oauth/start',{method:'POST',body:body(),headers:{origin}}),e);assert.equal(r.status,303);const url=new URL(r.headers.get('location')!);assert.equal(url.searchParams.get('scope'),scopes.ga4);assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.match(r.headers.get('set-cookie')!,/Secure; HttpOnly; SameSite=Lax/);});
test('callback rejects missing/mismatched state before token exchange',async()=>{assert.equal((await api(req('/api/google/oauth/callback?code=unknown&state=wrong'),env())).status,400);});
test('date validation rejects malformed, reversed and excessive ranges',()=>{assert.throws(()=>dates('2026-02-30','2026-03-01'));assert.throws(()=>dates('2026-09-01','2026-08-01'));assert.throws(()=>dates('2025-01-01','2026-01-01'));dates('2026-08-01','2026-08-28');});
test('GA4 report preserves key event rates, currency and coverage flags',async()=>{const original=globalThis.fetch;globalThis.fetch=async(input:any)=>new Response(JSON.stringify(String(input).includes('analyticsadmin')?{currencyCode:'USD',timeZone:'America/Los_Angeles'}:{rowCount:1,metadata:{subjectToThresholding:true},rows:[{dimensionValues:[{value:'/contact'}],metricValues:['4','6','1','3','3','127','0'].map(value=>({value}))}]}),{headers:{'content-type':'application/json'}});try{const r=await report('ga4','test',{id:'properties/123',name:'Example'},'2026-08-01','2026-08-28');assert.equal(r.rows[0][3],'1');assert.equal(r.account.currency,'USD');assert(r.limitations.some((l:string)=>l.includes('threshold')));}finally{globalThis.fetch=original;}});
test('Ads report converts cost micros once and preserves fractional conversions',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({results:[{campaign:{id:'7',name:'Example'},metrics:{costMicros:'123456789',conversions:'2.5',clicks:'8'}}]}));try{const r=await report('ads','test',{id:'123',manager:'456'},'2026-08-01','2026-08-28');assert.equal(r.rows[0][4],'123.456789');assert.equal(r.rows[0][5],'2.5');}finally{globalThis.fetch=original;}});
test('Worker keeps the static frontend and handles missing assets',async()=>{const worker=createWorker({'/index.html':{type:'text/html',data:btoa('asset')}});assert.equal((await worker.fetch(new Request(origin+'/'),env())).status,200);assert.equal((await worker.fetch(new Request(origin+'/missing'),env())).status,404);});

test('Worker sends readable HTML and exact binary bytes without precompression',async()=>{const html='<!doctype html><html><body>Subgrowth — Connections</body></html>';const htmlBytes=new TextEncoder().encode(html);const png=Uint8Array.from([137,80,78,71,13,10,26,10,0,255]);const encode=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes));const worker=createWorker({'/index.html':{type:'text/html; charset=utf-8',data:encode(htmlBytes)},'/logo.png':{type:'image/png',data:encode(png)}});const response=await worker.fetch(new Request(origin+'/'),env());assert.equal(response.headers.get('content-encoding'),null);assert.equal(response.headers.get('content-type'),'text/html; charset=utf-8');assert.equal(await response.text(),html);assert.deepEqual(new Uint8Array(await (await worker.fetch(new Request(origin+'/logo.png'),env())).arrayBuffer()),png);const head=await worker.fetch(new Request(origin+'/',{method:'HEAD'}),env());assert.equal(await head.text(),'');assert.equal(head.headers.get('content-encoding'),null);});
