'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,FlaskConical,Plus,ClipboardList,Download} from 'lucide-react';
import type {WorkspaceState} from '@/lib/domain/types';
import {dateInZone,dayOffset} from '@/lib/domain/types';
import type {PerformanceReport,PerformanceKind} from '@/lib/domain/performance';
import {actionDatasets,sourceKey,datasetMetrics,metricLabels,statusLabels,createAction,recordChange,checkResults,closeAction,updateAction,formatActionMetric,type ActionPlan,type ActionSeed,type ActionDataset,type ActionMetric,type ActionStatus} from '@/lib/domain/actions';
import {Modal,Badge,download} from './ui';

export default function ActionWorkbench({state,reports,sample,onSave,seed,onSeedHandled}:{state:WorkspaceState;reports:Partial<Record<PerformanceKind,PerformanceReport|null>>;sample:boolean;onSave:(state:WorkspaceState)=>Promise<void>;seed:ActionSeed|null;onSeedHandled:()=>void}){
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState('active'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const datasets=useMemo(()=>actionDatasets(state,reports,sample),[state,reports,sample]);
 const plans=state.actionPlans??[],active=plans.find(p=>p.id===selected);
 useEffect(()=>{if(seed){setCreating(true);setError('');}},[seed]);
 async function save(plan:ActionPlan){setBusy(true);setError('');try{if(!plans.some(p=>p.id===plan.id)&&plans.length>=200)throw new Error('This workspace supports up to 200 saved actions.');await onSave({...state,actionPlans:plans.some(p=>p.id===plan.id)?plans.map(p=>p.id===plan.id?plan:p):[plan,...plans]});}catch(e){setError((e as Error).message);throw e;}finally{setBusy(false);}}
 const visible=plans.filter(p=>filter==='all'||(filter==='active'?!['completed','cancelled'].includes(p.status):p.status===filter));
 return <section className="panel actions-panel" id="actions" aria-labelledby="actions-title"><div className="section-heading"><div><span className="eyebrow">ACT → MEASURE → LEARN</span><h2 id="actions-title">Actions & experiments</h2><p>Give a finding an owner. Record the change. See what happened.</p></div><button className="primary" disabled={state.mode==='cloud'} onClick={()=>{onSeedHandled();setCreating(true);setError('');}}><Plus size={16}/> New action</button></div>
 {state.mode==='cloud'?<p className="notice">Actions are available in company workspaces and the local demo. This separate Supabase workspace does not yet support action storage.</p>:<>
 <div className="action-stats">{(['planned','in_progress','measuring','completed'] as ActionStatus[]).map(status=><button key={status} onClick={()=>setFilter(status)} aria-pressed={filter===status}><strong>{plans.filter(p=>p.status===status).length}</strong><span>{statusLabels[status]}</span></button>)}</div>
 <div className="actions-toolbar"><label>Show actions<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active actions</option><option value="all">All actions</option>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><p className="subtle">{state.mode==='company'?'Saved for this brand and shared with your company team.':'Demo / sandbox actions stay in this browser.'} Assignment records responsibility; it does not send notifications.</p></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 <div className="action-cards">{visible.map(plan=><article key={plan.id} className="action-card"><div className="action-card-meta"><Badge>{plan.kind==='experiment'?<><FlaskConical size={13}/> Experiment</>:<><ClipboardList size={13}/> Task</>}</Badge><Badge>{statusLabels[plan.status]}</Badge>{plan.source?.origin==='sample'&&<Badge>SAMPLE</Badge>}</div><button className="card-title" onClick={()=>{setSelected(plan.id);setError('');}}><h3>{plan.title}</h3><ArrowRight size={18}/></button><p>{plan.hypothesis}</p><div className="action-card-owner"><span>{plan.owner}</span><span className={plan.dueDate&&plan.dueDate<dateInZone(new Date(),state.profile.timezone)&&!['completed','cancelled'].includes(plan.status)?'action-overdue':''}>{plan.dueDate?'Due '+plan.dueDate:'No due date'}</span></div>{plan.result?<div className="action-outcome"><strong>{resultLabel(plan)}</strong><span>{plan.result.percent===null?'Relative change unavailable: no positive baseline':`${plan.result.percent>0?'+':''}${plan.result.percent.toFixed(1)}% observed change`}</span></div>:plan.status==='measuring'?<p className="action-measuring">Measuring {plan.metric&&metricLabels[plan.metric]} · {plan.window} days after {plan.implementedAt}</p>:null}{plan.decision&&<p className="subtle">Decision: {plan.decision}</p>}</article>)}</div>
 {!visible.length&&<div className="action-empty"><ClipboardList size={27}/><h3>{plans.length?'No actions match this view.':'Turn your next finding into progress.'}</h3><p>{plans.length?'Choose another status to see your work.':'Open a campaign assessment or opportunity and choose Create action, or start a task here.'}</p></div>}
 </>}
 <Modal open={creating&&state.mode!=='cloud'} onClose={()=>{setCreating(false);onSeedHandled();}} title="Create an action" description="Plan the work and decide how you’ll know whether it helped." wide><ActionForm key={seed?.reference??'manual'} state={state} seed={seed} datasets={datasets} busy={busy} onCreate={async plan=>{await save(plan);setCreating(false);onSeedHandled();setFilter('active');setSelected(plan.id);setNotice('Action saved. No campaigns or external tools were changed.');}}/></Modal>
 <Modal open={!!active} onClose={()=>setSelected(null)} title={active?.title??'Action'} description="The plan, source evidence, implementation, and learning stay together." wide>{active&&<ActionDetail key={active.id+':'+active.updatedAt} plan={active} datasets={datasets} busy={busy} onSave={save}/>}</Modal>
 </section>;
}
function resultLabel(plan:ActionPlan){return plan.result?.outcome==='target_met'?'Improvement target met':plan.result?.outcome==='improved'?'Improved, below target':plan.result?.outcome==='worse'?'Moved against the goal':'No observed change';}
function ActionForm({state,seed,datasets,busy,onCreate}:{state:WorkspaceState;seed:ActionSeed|null;datasets:ActionDataset[];busy:boolean;onCreate:(p:ActionPlan)=>Promise<void>}){
 const initial=datasets.find(d=>seed?.source&&sourceKey(d.source)===sourceKey(seed.source));
 const [kind,setKind]=useState<'task'|'experiment'>(initial?'experiment':'task'),[title,setTitle]=useState(seed?.title??''),[owner,setOwner]=useState(''),[due,setDue]=useState(''),[hypothesis,setHypothesis]=useState(''),[dataKey,setDataKey]=useState(initial?sourceKey(initial.source):''),[metric,setMetric]=useState<ActionMetric>(seed?.metric??'sessions'),[direction,setDirection]=useState<'increase'|'decrease'>(seed?.metric==='cpa'||seed?.metric==='spend'?'decrease':'increase'),[target,setTarget]=useState(10),[window,setWindow]=useState<7|14|28>(7),[error,setError]=useState('');
 const dataset=datasets.find(d=>sourceKey(d.source)===dataKey),metrics=dataset?datasetMetrics(dataset):[],chosen=metrics.includes(metric)?metric:metrics[0];
 return <form onSubmit={async e=>{e.preventDefault();setError('');try{await onCreate(createAction({brandId:state.id,timezone:state.profile.timezone,kind,title,owner,dueDate:due,hypothesis,direction,targetPercent:target,window,lagDays:dataset?.lagDays??7,evidence:{title:seed?.title??title,summary:seed?.summary??hypothesis,reference:seed?.reference??'Manually created action',capturedAt:new Date().toISOString()},...(dataset?{source:dataset.source,metric:chosen}:{})}));}catch(e){setError((e as Error).message);}}}>
 <div className="form-grid"><label>Type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="task">Task — complete a piece of work</option><option value="experiment">Experiment — measure a change</option></select></label><label>Owner<input required maxLength={120} value={owner} onChange={e=>setOwner(e.target.value)} placeholder="Name or team"/></label></div><label>Action title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Test a shorter signup form"/></label><label>{kind==='experiment'?'Hypothesis / expected change':'What needs to be done?'}<textarea required maxLength={2000} value={hypothesis} onChange={e=>setHypothesis(e.target.value)} placeholder={kind==='experiment'?'If we change… we expect… because…':'Describe the work and the acceptance criteria.'}/></label><label>Due date (optional)<input type="date" value={due} onInput={e=>setDue(e.currentTarget.value)} onChange={e=>setDue(e.target.value)}/></label>
 {seed&&<div className="notice"><strong>Linked finding</strong><p>{seed.summary}</p><small>{seed.reference}</small></div>}
 {kind==='experiment'&&<fieldset className="action-measurement-plan"><legend>Success measure</legend><label>Report / campaign / channel<select required value={dataKey} onChange={e=>setDataKey(e.target.value)}><option value="">Choose matching daily evidence</option>{datasets.map(d=><option key={sourceKey(d.source)} value={sourceKey(d.source)}>{d.label} · {d.source.account}</option>)}</select></label>{!datasets.length&&<p className="notice">Load a performance report or import a daily CSV first. You can create a task now.</p>}<div className="form-grid"><label>Primary metric<select required value={chosen??''} onChange={e=>{setMetric(e.target.value as ActionMetric);setDirection(['cpa','spend'].includes(e.target.value)?'decrease':'increase');}}><option value="" disabled>Choose a metric</option>{metrics.map(m=><option value={m} key={m}>{metricLabels[m]}</option>)}</select></label><label>Success direction<select value={direction} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="increase">Increase</option><option value="decrease">Decrease</option></select></label><label>Relative improvement target (%)<input type="number" required min="0.1" max="100" step="0.1" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label>Before / after window<select value={window} onChange={e=>setWindow(Number(e.target.value) as typeof window)}>{[7,14,28].map(d=><option key={d} value={d}>{d} complete days each</option>)}</select></label></div><p className="subtle">Compares the days immediately before the change with an equal period after it. The implementation day is excluded. {dataset?.lagDays??7} reporting-buffer days must pass before the after period can be checked. Rates use summed numerators and denominators.</p>{dataset?.source.origin==='sample'&&<p className="notice">This experiment uses fictional sample data. Its results illustrate the workflow and do not represent a real business.</p>}</fieldset>}
 {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Create action'}</button>
 </form>;
}
function ActionDetail({plan,datasets,busy,onSave}:{plan:ActionPlan;datasets:ActionDataset[];busy:boolean;onSave:(p:ActionPlan)=>Promise<void>}){
 const [owner,setOwner]=useState(plan.owner),[due,setDue]=useState(plan.dueDate),[date,setDate]=useState(dateInZone(new Date(),plan.source?.timezone??plan.timezone??'UTC')),[notes,setNotes]=useState(''),[decision,setDecision]=useState<ActionPlan['decision']>(plan.result?undefined:'inconclusive'),[learning,setLearning]=useState(''),[error,setError]=useState(''),[cancel,setCancel]=useState(false);
 async function run(fn:()=>ActionPlan){setError('');try{await onSave(fn());}catch(e){setError((e as Error).message);}}
 const closed=['completed','cancelled'].includes(plan.status),started=plan.status==='measuring',value=(v:number)=>formatActionMetric(v,plan.metric!,plan.source?.currency);
 return <div className="action-detail"><div className="action-row"><Badge>{plan.kind}</Badge><Badge>{statusLabels[plan.status]}</Badge>{plan.source?.origin==='sample'&&<Badge>SAMPLE DATA</Badge>}<button className="text-button" onClick={()=>download('growthos-action-'+plan.id+'.json',JSON.stringify(plan,null,2),'application/json')}><Download size={14}/> Export record</button></div><p>{plan.hypothesis}</p><details className="action-evidence"><summary>Original finding & measurement plan</summary><p>{plan.evidence.summary}</p><small>{plan.evidence.reference} · captured {new Date(plan.evidence.capturedAt).toLocaleString()}</small>{plan.source&&<><p>{plan.source.origin} · {plan.source.account} · {plan.source.entity}<br/>{plan.source.timezone} · {plan.source.currency} · {plan.source.definition}</p><p>{metricLabels[plan.metric!]}: {plan.direction} by {plan.targetPercent}% across equal {plan.window}-day windows, with a {plan.lagDays}-day reporting buffer.</p></>}</details>
 {error&&<p className="error" role="alert">{error}</p>}
 {!closed&&<form onSubmit={e=>{e.preventDefault();void run(()=>{if(!owner.trim())throw new Error('Assign an owner.');return updateAction(plan,{owner:owner.trim(),dueDate:due},'Assignment or due date updated.');});}}><div className="form-grid"><label>Assigned owner<input required maxLength={120} value={owner} onChange={e=>setOwner(e.target.value)}/></label><label>Due date<input type="date" value={due} onInput={e=>setDue(e.currentTarget.value)} onChange={e=>setDue(e.target.value)}/></label></div><button className="secondary" disabled={busy||owner===plan.owner&&due===plan.dueDate}>Save assignment</button></form>}
 {['planned','in_progress'].includes(plan.status)&&<><div className="action-row">{plan.status==='planned'&&<button className="secondary" disabled={busy} onClick={()=>void run(()=>updateAction(plan,{status:'in_progress'},'Work started.'))}>Start work <ArrowRight size={15}/></button>}</div><form className="action-log-form" onSubmit={e=>{e.preventDefault();void run(()=>recordChange(plan,date,notes,datasets));}}><h3>{plan.kind==='task'?'Complete the task':'Record the implementation'}</h3><p>Make the change in the relevant tool, then record it here.</p><label>{plan.kind==='task'?'Completion date':'Implementation date'}<input required type="date" max={dateInZone(new Date(),plan.source?.timezone??plan.timezone??'UTC')} value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)}/></label><label>{plan.kind==='task'?'What was completed?':'What exactly changed?'}<textarea required maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Include the destination and enough detail for a teammate to understand the change."/></label><button className="primary" disabled={busy}><CheckCircle2 size={16}/>{plan.kind==='task'?'Complete task':'Save change & start measuring'}</button></form></>}
 {plan.implementedAt&&<div className="notice"><strong>{plan.kind==='task'?'Completed':'Implemented'} {plan.implementedAt}</strong><p>{plan.changeNotes}</p></div>}
 {(started||plan.result)&&<div className="action-results"><h3>Before & after</h3><p>{plan.window} days before the change vs {plan.window} days after. Implementation day excluded.</p>{plan.implementedAt&&<p className="subtle">Baseline: {dayOffset(plan.implementedAt,-plan.window)} – {dayOffset(plan.implementedAt,-1)}<br/>After: {dayOffset(plan.implementedAt,1)} – {dayOffset(plan.implementedAt,plan.window)} · eligible from {dayOffset(plan.implementedAt,plan.window+plan.lagDays)} ({plan.source?.timezone})</p>}{plan.result?<><div className="action-comparison"><div><small>BEFORE</small><strong>{value(plan.result.baseline.value)}</strong></div><ArrowRight/><div><small>AFTER</small><strong>{value(plan.result.after.value)}</strong></div><div><small>OBSERVED CHANGE</small><strong>{plan.result.percent===null?'No positive % baseline':`${plan.result.percent>0?'+':''}${plan.result.percent.toFixed(1)}%`}</strong></div></div><p><strong>{resultLabel(plan)}</strong> · target {plan.targetPercent}% {plan.direction}</p><small>Checked {new Date(plan.result.checkedAt).toLocaleString()} · before source collected {new Date(plan.result.baseline.collectedAt).toLocaleString()} · after source collected {new Date(plan.result.after.collectedAt).toLocaleString()}</small></>:<p className="notice">{plan.baseline?'Baseline saved. Waiting for a complete after period.':'Baseline pending. Check results when the matching daily history covers the comparison window.'}</p>}{plan.measurementNote&&<p className="notice">{plan.measurementNote}</p>}{started&&<button className="secondary" disabled={busy} onClick={()=>void run(()=>checkResults(plan,datasets))}>Check results from loaded data</button>}<p className="subtle">Refresh Performance or import the matching daily CSV before checking. Checks run only when requested. Saved baselines remain fixed; incomplete coverage, changed sources, or zero-denominator rates cannot produce a comparison. Before/after movement does not prove causation: review traffic mix, tracking, seasonality, and other changes.</p></div>}
 {started&&<form className="action-log-form" onSubmit={e=>{e.preventDefault();void run(()=>closeAction(plan,decision,learning));}}><h3>Review the outcome</h3><label>Decision<select required value={decision??''} onChange={e=>setDecision(e.target.value as ActionPlan['decision'])}><option value="" disabled>Choose a decision</option>{plan.result&&<><option value="keep">Keep the change</option><option value="iterate">Iterate with another experiment</option><option value="revert">Revert in the source tool</option></>}<option value="inconclusive">Inconclusive / insufficient evidence</option></select></label><label>What did you learn?<textarea required maxLength={4000} value={learning} onChange={e=>setLearning(e.target.value)} placeholder="Explain your decision, other possible causes, and the next step."/></label><button className="primary" disabled={busy}>Save review & close experiment</button><p className="subtle">This records your decision; it does not change a campaign or revert anything externally.</p></form>}
 {closed&&<div className="notice"><strong>{plan.decision?'Decision: '+plan.decision:statusLabels[plan.status]}</strong><p>{plan.learning}</p><p>Owner: {plan.owner} · {plan.dueDate?'Due '+plan.dueDate:'No due date'}</p></div>}
 {!closed&&<div className="action-cancel"><button className="text-button muted" disabled={busy} onClick={()=>setCancel(!cancel)}>Cancel action</button>{cancel&&<form onSubmit={e=>{e.preventDefault();void run(()=>{if(!learning.trim())throw new Error('Add a cancellation reason.');return updateAction(plan,{status:'cancelled',learning:learning.trim()},'Action cancelled.');});}}><label>Why cancel?<textarea required maxLength={4000} value={learning} onChange={e=>setLearning(e.target.value)}/></label><button className="secondary" disabled={busy}>Confirm cancellation</button></form>}</div>}
 <details><summary>Activity ({plan.history.length})</summary>{plan.history.slice().reverse().map((item,i)=><p key={i}><small>{new Date(item.at).toLocaleString()}</small><br/>{item.message}</p>)}</details>
 </div>;
}
