'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Plus,Building2} from 'lucide-react';
import {companyRequest,type CompanyAccess} from './team-settings';
import {Modal} from './ui';
export type Brand={id:string;name:string;website:string;primary?:boolean};
export type BrandContext={generation:number;access:CompanyAccess;brand:Brand;brands:Brand[];select:(id:string)=>void;manage:()=>void;rename:(name:string,website:string)=>void};
export function BrandGate({children}:{children:(context:BrandContext|null)=>ReactNode}){
 const [generation,setGeneration]=useState(0);
 const [access,setAccess]=useState<CompanyAccess|null>(null),[brands,setBrands]=useState<Brand[]>([]),[chosen,setChosen]=useState(''),[local,setLocal]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[manage,setManage]=useState(false),[name,setName]=useState(''),[website,setWebsite]=useState(''),[saving,setSaving]=useState(false),[formError,setFormError]=useState('');
 async function reload(){setLoading(true);setError('');try{const me=await companyRequest('me');if(me.role==='owner')await companyRequest('migrate',{});const data=await companyRequest('brands');setAccess(me);setBrands(data.brands);const stored=new URL(location.href).searchParams.get('brand')??localStorage.getItem('growthos:brand:'+me.companyId);setChosen(data.brands.some((b:Brand)=>b.id===stored)?stored:data.brands[0].id);const url=new URL(location.href);if(url.searchParams.has('brand')){url.searchParams.delete('brand');history.replaceState(null,'',url);}}catch(e){if(['localhost','127.0.0.1'].includes(location.hostname))setLocal(true);else setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void reload();},[]);
 function select(id:string){if(!access||!brands.some(b=>b.id===id))return;localStorage.setItem('growthos:brand:'+access.companyId,id);localStorage.setItem('growthos:active','company');const url=new URL(location.href);url.searchParams.delete('brand');history.replaceState(null,'',url);setChosen(id);setGeneration(v=>v+1);setManage(false);}
 if(local)return children(null);
 if(loading)return <div className="boot" role="status">Opening your brands…</div>;
 if(error)return <div className="panel brand-load-error"><h1>Could not open your brands</h1><p role="alert">{error}</p><button className="primary" onClick={()=>void reload()}>Try again</button></div>;
 const brand=brands.find(b=>b.id===chosen);if(!brand||!access)return null;
 const context:BrandContext={generation,access,brand,brands,select,manage:()=>setManage(true),rename:(name,website)=>setBrands(current=>current.map(b=>b.id===chosen?{...b,name,website}:b))};
 return <>{children(context)}<Modal open={manage} onClose={()=>setManage(false)} title="Your brands" description="Each brand has its own connections, imports, insights, and drafts. Company teammates can work across these brands."><div className="workspace-options">{brands.map(b=><button key={b.id} onClick={()=>select(b.id)} aria-current={b.id===chosen?'true':undefined}><Building2 size={19}/><span><strong>{b.name}</strong><small>{b.website||'Finish the brand profile in Brand settings'}</small></span>{b.id===chosen&&<span className="badge">Current</span>}</button>)}</div>{access.canAdmin?<form className="brand-create" onSubmit={async e=>{e.preventDefault();if(saving)return;setSaving(true);setFormError('');try{const data=await companyRequest('brands',{name,website});setBrands(b=>[...b,data.brand]);localStorage.setItem('growthos:brand:'+access.companyId,data.brand.id);setChosen(data.brand.id);setManage(false);setName('');setWebsite('');}catch(e){setFormError((e as Error).message);}finally{setSaving(false);}}}><h3>Add a brand</h3><label>Brand name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Your client’s company"/></label><label>Website<input type="url" required maxLength={2000} value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://example.com"/></label>{formError&&<p className="error" role="alert">{formError}</p>}<button className="primary" disabled={saving}><Plus size={16}/>{saving?'Creating…':'Create brand'}</button><p className="subtle">New brands start empty. Add their Google connections or import their CSV reports.</p></form>:<p>Ask a company admin to add a brand.</p>}</Modal></>;
}
export function BrandSelector({context,name,busy,isCompany}:{context:BrandContext|null;name:string;busy:boolean;isCompany:boolean}){
 if(!context)return <div className="workspace-switch"><span className="workspace-avatar">{name[0]||'B'}</span><span><strong>{name||'Local preview'}</strong><small>Local workspace</small></span></div>;
 return <div className="brand-navigation"><div className="workspace-switch"><span className="workspace-avatar">{(isCompany?name:context.brand.name)[0]||'B'}</span>{context.brands.length>1?<label className="brand-picker-label">WORKING ON<select aria-label="Working brand" disabled={busy} value={context.brand.id} onChange={e=>context.select(e.target.value)}>{context.brands.map(b=><option key={b.id} value={b.id}>{b.id===context.brand.id&&isCompany?name:b.name}</option>)}</select></label>:<span><strong>{isCompany?name:context.brand.name}</strong><small>Your brand</small></span>}</div><button className="text-button manage-brands" disabled={busy} onClick={context.manage}>Manage brands</button></div>;
}
