'use client';
import {useState} from 'react';
import {ArrowUpRight,Globe,LoaderCircle,FlaskConical} from 'lucide-react';
import type {Profile} from '@/lib/domain/types';

type Evidence={url:string;title:string};
type Finding={area:string;observation:string;evidence:Evidence[];verified:boolean};
type Site={id:string;name:string;website:string;domain:string;findings:Finding[];limitations:string;covered:boolean};
type Opportunity={title:string;area:string;priority:string;rationale:string;change:string;measurement:string;evidence:Evidence[]};
type Entry={id:string;name:string;website:string;domain:string;status:string};
export type Comparison={attempt:null|{at:string;status:string;error:string|null};daily:{date:string;count:number};report:null|{sites:Site[];opportunities:Opportunity[];limitations:string;filteredOpportunities:number;completedAt:string;model:string;usage:{inputTokens:number;outputTokens:number;searchCalls:number};targets:{brand:{name:string;website:string;products:string;audience:string;geography:string};competitors:{id:string;name:string;website:string}[]}}};
function Sources({links}:{links:Evidence[]}){return <div className="comparison-sources">{links.map((link,i)=><a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer" title={link.title}>{new URL(link.url).hostname.replace(/^www\./,'')} · source {i+1}<ArrowUpRight size={12}/></a>)}</div>;}
export default function CompetitorComparison({entries,comparison,configured,canScan,loading,profile,onCompare,onConnect}:{entries:Entry[];comparison?:Comparison;configured:boolean;canScan:boolean;loading:boolean;profile:Profile;onCompare:(ids:string[])=>Promise<unknown>;onConnect:()=>void}){
 const [selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const confirmed=entries.filter(e=>e.status==='confirmed'),ids=selected.filter(id=>confirmed.some(e=>e.id===id));
 const running=busy||Boolean(comparison?.attempt?.status==='running'&&Date.now()-Date.parse(comparison.attempt.at)<180000);
 const count=comparison?.daily.date===new Date().toISOString().slice(0,10)?comparison.daily.count:0,report=comparison?.report;
 const stale=report&&(Object.entries(report.targets.brand).some(([key,value])=>String(profile[key as keyof Profile]??'').trim().replace(/\/$/,'')!==value.replace(/\/$/,''))||report.targets.competitors.some(c=>!confirmed.some(e=>e.id===c.id&&e.name===c.name&&e.website===c.website)));
 async function compare(){setBusy(true);setError('');try{await onCompare(ids);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <>
  <section className="panel comparison-panel" aria-labelledby="comparison-heading">
   <div className="section-heading"><div><div className="eyebrow">TURN RESEARCH INTO YOUR NEXT TEST</div><h2 id="comparison-heading">Compare my brand</h2><p>See what other websites do well—and what you could test to win more business.</p></div><Globe size={26} aria-hidden="true"/></div>
   <p className="subtle">Choose up to 3 confirmed competitors. We research your website alongside theirs for messaging, offers, trust, conversion paths, and content. This is a review of available website text, not a visual or technical audit.</p>
   {confirmed.length?<fieldset className="comparison-picker" disabled={running||loading}><legend>Compare {profile.name} with</legend>{confirmed.map(entry=><label key={entry.id}><input type="checkbox" checked={ids.includes(entry.id)} disabled={!ids.includes(entry.id)&&ids.length>=3} onChange={e=>setSelected(e.target.checked?[...ids,entry.id]:ids.filter(id=>id!==entry.id))}/><span><strong>{entry.name}</strong><small>{entry.domain}</small></span></label>)}</fieldset>:<p className="notice">Confirm a suggestion or add a competitor manually to start comparing.</p>}
   <div className="comparison-controls"><button className="primary" disabled={running||loading||!configured||!canScan||!ids.length||count>=3} onClick={()=>void compare()}>{running?<LoaderCircle size={17} className="spin"/>:<FlaskConical size={17}/>} {running?'Researching websites…':'Compare websites'}</button>{canScan&&!configured&&<button className="secondary" onClick={onConnect}>Connect OpenAI</button>}<small>{count} of 3 comparisons used today · UTC · uses your OpenAI API plan</small></div>
   {!canScan&&<p className="subtle">A company admin can run comparisons. Teammates can read the saved report.</p>}
   {running&&<p className="notice" role="status">Checking public pages and grounding recommendations in sources. This can take up to two minutes. The last saved report remains below; use Reload list if you return later.</p>}
   {(error||comparison?.attempt?.error)&&<p className="error" role="alert">{error||comparison?.attempt?.error}</p>}
  </section>
  {report&&<section className="comparison-report" aria-label="Saved website comparison">
   <div className="section-heading"><div><div className="eyebrow">WEBSITE COMPARISON</div><h2>Ideas to earn the next customer.</h2><p>Researched {new Date(report.completedAt).toLocaleString()} · {report.sites.filter(s=>s.covered).length} of {report.sites.length} websites have usable evidence</p></div></div>
   {stale&&<p className="notice">Your brand context or competitor selections have changed since this report. These findings describe the saved comparison; run another to update them.</p>}
   <p className="subtle">Priorities are AI judgments. These are hypotheses to test, not proof of competitor performance or promises of more sales.</p>
   <div className="comparison-opportunities">{report.opportunities.map((o,i)=><article key={i} className="panel comparison-opportunity"><div className="comparison-opportunity-top"><span className="comparison-number">{String(i+1).padStart(2,'0')}</span><span className="badge">{o.priority} priority · {o.area}</span></div><h3>{o.title}</h3><p>{o.rationale}</p><h4>Change to test</h4><p>{o.change}</p><h4>How to measure</h4><p>{o.measurement}</p><Sources links={o.evidence}/></article>)}</div>
   {!report.opportunities.length&&<p className="notice">No recommendations met the evidence requirement for both your brand and a competitor. Review the findings below or try another comparison.</p>}
   <section className="panel"><div className="section-heading"><div><h2>What the websites show</h2><p>Observed details and sources. “Not verified” does not mean a feature is missing.</p></div></div><div className="comparison-table-scroll" role="region" aria-label="Website findings, scroll horizontally" tabIndex={0}><table className="comparison-table"><thead><tr><th scope="col">Area</th>{report.sites.map(s=><th scope="col" key={s.id}><span className="eyebrow">{s.id==='brand'?'YOUR BRAND':'COMPETITOR'}</span><a href={s.website} target="_blank" rel="noopener noreferrer">{s.name}<ArrowUpRight size={13}/></a></th>)}</tr></thead><tbody>{['Positioning','Offers','Trust','Conversion','Content'].map(area=><tr key={area}><th scope="row">{area}</th>{report.sites.map(site=>{const finding=site.findings.find(f=>f.area===area);return <td key={site.id} className={!finding?.verified?'comparison-unverified':''}><p>{finding?.observation??'Not verified in this scan.'}</p><Sources links={finding?.evidence??[]}/></td>;})}</tr>)}</tbody></table></div></section>
   <details className="panel comparison-limitations"><summary>Research coverage and limitations</summary><p>{report.limitations||'Website access and search coverage can be incomplete. Verify the source pages before acting.'}</p>{report.sites.filter(s=>s.limitations).map(s=><p key={s.id}><strong>{s.name}:</strong> {s.limitations}</p>)}<p>Search results may be cached. This report does not test forms, mobile layouts, page speed, or actual conversion rates. Ads are not included. No background monitoring runs.</p>{report.filteredOpportunities>0&&<p>{report.filteredOpportunities} proposed recommendations were excluded because their evidence could not be verified.</p>}<p className="subtle">{report.model} · {report.usage.searchCalls} web tool calls · {report.usage.inputTokens.toLocaleString()} input / {report.usage.outputTokens.toLocaleString()} output tokens. Usage is not an invoice.</p></details>
  </section>}
  <section className="panel competitor-ads"><div className="section-heading"><div><div className="eyebrow">PUBLIC AD RESEARCH</div><h2>Explore their ads</h2><p>Look for offers, hooks, creative, and the landing pages they promote.</p></div><span className="badge">Manual library lookup</span></div><p>Open Google’s Ads Transparency Center or Meta’s Ad Library. Verify the advertiser matches the business and set the country and dates. A search link is not evidence that a company is running ads.</p>{confirmed.length>0?<div className="competitor-ad-links">{confirmed.map(e=><div key={e.id}><strong>{e.name}</strong><a href={'https://adstransparency.google.com/?domain='+encodeURIComponent(e.domain)+'&region=anywhere'} target="_blank" rel="noopener noreferrer">Google ads<ArrowUpRight size={14}/></a><a href={'https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=ALL&q='+encodeURIComponent(e.name)+'&search_type=keyword_unordered'} target="_blank" rel="noopener noreferrer">Meta ads<ArrowUpRight size={14}/></a></div>)}</div>:<p className="subtle">Library links appear for your confirmed competitors.</p>}<p className="subtle">Automatic ad collection is not connected. Public libraries do not reveal competitor leads, sales, or ROAS; available fields and coverage vary. Your Google Ads connection only reports on accounts you can access.</p></section>
 </>;
}
