'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,Plus,Check,X,RotateCcw,ExternalLink,LoaderCircle,ShieldCheck} from 'lucide-react';
import {manualCompetitor} from '@/server/competitor-core.mjs';
import type {WorkspaceState} from '@/lib/domain/types';
import {Modal,Badge,Empty} from './ui';
type Status='suggested'|'confirmed'|'dismissed';
type Entry={id:string;name:string;website:string;domain:string;reason:string;evidence:{url:string;title:string}[];status:Status;source:'manual'|'scan';createdAt:string;reviewedAt:string|null};
type Research={revision:number;entries:Entry[];attempt:null|{id:string;at:string;status:string;error:string|null};daily:{date:string;count:number};lastScan:null|{at:string;completedAt:string;added:number;filtered:number;limitations:string;model:string;usage:{inputTokens:number;outputTokens:number;searchCalls:number};profile:{name:string;website:string;products:string;audience:string;geography:string}}};
type Payload={research:Research;configured:boolean;canScan:boolean;model:string;error?:string};
export default function CompetitorWorkbench({state,brandId,onSave,onBrand}:{state:WorkspaceState;brandId?:string;onSave:(s:WorkspaceState)=>Promise<void>;onBrand:()=>void}){
 const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[scanning,setScanning]=useState(false),[loading,setLoading]=useState(Boolean(brandId)),[filter,setFilter]=useState<Status>('suggested'),[manual,setManual]=useState(false),[name,setName]=useState(''),[website,setWebsite]=useState(''),[formError,setFormError]=useState(''),[connect,setConnect]=useState(false),[keyFile,setKeyFile]=useState<File|null>(null),[connectionError,setConnectionError]=useState('');
 const mounted=useRef(true),started=useRef(false);
 async function request(path:string,body?:unknown){const res=await fetch('/api/competitors/'+path+'?brand='+encodeURIComponent(brandId??''),{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const payload=await res.json();if(mounted.current&&payload.research)setData(payload);if(!res.ok)throw new Error(payload.error??'Competitor request failed.');return payload as Payload;}
 async function scan(automatic=false){setScanning(true);setError('');try{await request('scan',{automatic});}catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setScanning(false);}}
 async function reload(){setLoading(true);setError('');try{await request('sync',{});}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{mounted.current=true;if(brandId&&!started.current){started.current=true;void (async()=>{try{const next=await request('sync',{});if(mounted.current&&next.configured&&next.canScan&&state.profile.discoverCompetitors&&!next.research.attempt)await scan(true);}catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setLoading(false);}})();}return()=>{mounted.current=false;};},[brandId]);
 const manualEntries:Entry[]=(state.profile.competitorEntries??[]).map((e,i)=>({id:'manual-'+i,name:e.name,website:e.website,domain: (()=>{try{return new URL(e.website).hostname;}catch{return e.website;}})(),reason:'Added during brand setup.',evidence:[],status:'confirmed',source:'manual',createdAt:'',reviewedAt:null}));
 const entries=brandId?(data?.research.entries??[]):manualEntries,view=brandId?filter:'confirmed',shown=entries.filter(e=>e.status===view);
 const running=scanning||Boolean(data?.research.attempt?.status==='running'&&Date.now()-Date.parse(data.research.attempt.at)<180000);
 const attempts=data?.research.daily.date===new Date().toISOString().slice(0,10)?data.research.daily.count:0;
 async function review(entry:Entry,status:Status){setBusy(true);setError('');try{await request('review',{id:entry.id,status,expectedRevision:data?.research.revision});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function connectKey(){setBusy(true);setConnectionError('');try{if(!keyFile||keyFile.size>20000)throw new Error('Choose a small env file containing OPENAI_API_KEY.');const text=await keyFile.text();const match=text.match(/^\s*(?:export\s+)?OPENAI_API_KEY\s*=\s*["']?(sk-[A-Za-z0-9_-]+)["']?\s*$/m);if(!match)throw new Error('No OPENAI_API_KEY was found in this file.');await request('configure',{token:match[1]});setKeyFile(null);setConnect(false);await reload();}catch(e){setConnectionError((e as Error).message);}finally{setBusy(false);}}
 async function add(){setBusy(true);setFormError('');try{const entry=manualCompetitor({name,website},state.profile.website);if(brandId)await request('add',{...entry,expectedRevision:data?.research.revision});else{const prior=state.profile.competitorEntries??[];if(prior.some(p=>{try{return manualCompetitor(p,state.profile.website).domain===entry.domain;}catch{return false;}}))throw new Error('That website is already on your list.');await onSave({...state,profile:{...state.profile,competitorEntries:[...prior,{name:entry.name,website:entry.website}]}});}setManual(false);setName('');setWebsite('');setFilter('confirmed');}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="page-heading"><div><div className="eyebrow">COMPETITOR DISCOVERY</div><h1>Know who’s in your market.</h1><p>Find possible competitors. Decide who belongs on your list.</p></div><button className="secondary" disabled={busy||loading} onClick={()=>{setFormError('');setManual(true);}}><Plus size={17}/>Add manually</button></div>
  <section className="panel competitor-scan-panel"><div><span className="eyebrow">DISCOVER → REVIEW → CONFIRM</span><h2>A shortlist, with the evidence.</h2><p>Search for businesses offering similar products or services to the same audience and area. Every suggestion stays unconfirmed until your team reviews it.</p><div className="competitor-context"><span>{state.profile.products||'Add products or services'}</span><span>{state.profile.geography||'Add a location'}</span><button className="text-button" onClick={onBrand}>Edit brand context</button></div></div><div className="competitor-scan-action"><button className="primary" disabled={!brandId||!data?.configured||!data.canScan||running||loading||attempts>=3} onClick={()=>void scan()}>{running?<LoaderCircle size={17} className="spin"/>:<Search size={17}/>} {running?'Finding competitors…':'Find competitors'}</button><small>{brandId?`${attempts} of 3 scans used today · resets at midnight UTC`:'Live scans require a company workspace'}</small>{brandId&&!loading&&!data?.configured&&<p className="subtle">An admin needs to set up the website’s OpenAI API key.</p>}{data?.canScan&&<button className="text-button competitor-connect" onClick={()=>{setConnectionError('');setConnect(true);}}>{data.configured?'Manage OpenAI connection':'Connect OpenAI'}</button>}{data&&!data.canScan&&<p className="subtle">An admin can run scans. Teammates can add and review competitors.</p>}</div></section>
  <p className="competitor-disclosure"><ShieldCheck size={17}/>Only the selected brand’s name, website, services, audience, and location are sent to OpenAI for discovery. Scans use your API plan. They run after opted-in onboarding or when an admin starts one; there is no scheduled background monitoring.</p>
  {(error||data?.research.attempt?.error)&&<div className="error" role="alert">{error||data?.research.attempt?.error}</div>}
  {running&&<div className="notice" role="status">Searching public sources and checking possible matches. This can take around a minute. You can review saved competitors while it runs.</div>}
  <section className="panel"><div className="section-heading"><div><h2>Your competitor list</h2><p>Saved separately for {state.profile.name}. Confirmed means approved by your team.</p></div>{brandId&&<button className="text-button" disabled={busy||loading} onClick={()=>void reload()}><RotateCcw size={15}/>Reload list</button>}</div>
   {brandId&&<div className="tabs competitor-tabs" aria-label="Competitor review status">{(['suggested','confirmed','dismissed'] as Status[]).map(s=><button key={s} className={view===s?'selected':''} aria-pressed={view===s} onClick={()=>setFilter(s)}>{s==='suggested'?'Needs review':s==='confirmed'?'Confirmed':'Dismissed'} <span>{entries.filter(e=>e.status===s).length}</span></button>)}</div>}
   {loading?<p role="status">Loading this brand’s competitors…</p>:!shown.length?<Empty title={view==='suggested'?'No suggestions waiting for review':view==='confirmed'?'No confirmed competitors yet':'No dismissed suggestions'} description={view==='suggested'?'Run a scan, or add a competitor you already know. A scan may return fewer matches when evidence is limited.':view==='confirmed'?'Confirm a suggested match or add a business manually.':'Dismissed businesses stay here and are excluded from future scans.'}/>:<div className="competitor-cards">{shown.map(entry=><article className="competitor-card" key={entry.id}><div className="competitor-card-heading"><span className="competitor-initial">{entry.name[0]}</span><div><h3>{entry.name}</h3><a href={entry.website} target="_blank" rel="noopener noreferrer">{entry.domain}<ExternalLink size={13}/></a></div><Badge>{entry.source==='manual'?'Added manually':'Web discovery'}</Badge></div><strong className="competitor-label">{entry.source==='scan'?'Why this could be a match':'Your team’s selection'}</strong><p>{entry.reason}</p>{entry.evidence.length>0&&<div className="competitor-evidence"><strong>Supporting sources</strong>{entry.evidence.map(link=><a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer">{link.title}<ExternalLink size={13}/></a>)}<small>Found {new Date(entry.createdAt).toLocaleDateString()} · AI-suggested fit; verify the service area and offering.</small></div>}{brandId&&<div className="action-row">{entry.status!=='confirmed'&&<button className="primary" disabled={busy} onClick={()=>void review(entry,'confirmed')}><Check size={16}/>Yes, a competitor</button>}{entry.status!=='dismissed'&&<button className="secondary" disabled={busy} onClick={()=>void review(entry,'dismissed')}><X size={16}/>{entry.status==='confirmed'?'Remove from confirmed':'Not a competitor'}</button>}{entry.status==='dismissed'&&<button className="secondary" disabled={busy} onClick={()=>void review(entry,'suggested')}><RotateCcw size={15}/>Review again</button>}</div>}</article>)}</div>}
  </section>
  {data?.research.lastScan&&<details className="panel competitor-scan-details"><summary>Last scan · {new Date(data.research.lastScan.completedAt).toLocaleString()}</summary><p>{data.research.lastScan.added} new suggestions added. {data.research.lastScan.filtered>0?`${data.research.lastScan.filtered} results were excluded because they lacked usable evidence or duplicated a business.`:''}</p><p>{data.research.lastScan.limitations||'Search coverage is incomplete. A missing business does not mean it is not a competitor.'}</p><p className="subtle">Model: {data.research.lastScan.model} · {data.research.lastScan.usage.searchCalls} search tool calls · {data.research.lastScan.usage.inputTokens.toLocaleString()} input / {data.research.lastScan.usage.outputTokens.toLocaleString()} output tokens. Costs are billed by OpenAI; this is not an invoice.</p><p className="subtle">Search context: {data.research.lastScan.profile.products} · {data.research.lastScan.profile.geography}</p></details>}
  {state.profile.competitors&&<details className="panel"><summary>Earlier competitor notes</summary><p>{state.profile.competitors}</p><p className="subtle">These notes are preserved. Add each business with its website to include it in the review list.</p></details>}
  <p className="subtle">Discovery finds possible competitors. It does not yet track website changes, pricing history, competitor ad spend, or keyword performance.</p>
  <Modal open={connect} onClose={()=>{setConnect(false);setKeyFile(null);}} title="Connect OpenAI" description="Use your company’s API key for competitor discovery across its brands."><form onSubmit={e=>{e.preventDefault();void connectKey();}}><p>Select the local env file containing OPENAI_API_KEY. Only that key is sent to this company website and stored encrypted on the server. Other file contents are not uploaded. The saved key is never returned to browsers.</p><label>API key env file<input type="file" required onChange={e=>setKeyFile(e.target.files?.[0]??null)}/></label><p className="subtle">This replaces the current discovery key if one is already connected. OpenAI bills API usage to its project. Confirm model access and spending limits in your OpenAI account.</p>{connectionError&&<p className="error" role="alert">{connectionError}</p>}<button className="primary" disabled={busy||!keyFile}>{busy?'Verifying…':'Connect API key'}</button></form></Modal>
  <Modal open={manual} onClose={()=>setManual(false)} title="Add a competitor" description="A business you add manually goes directly into your confirmed list."><form onSubmit={e=>{e.preventDefault();void add();}}><label>Business name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Website<input required maxLength={2000} placeholder="https://competitor.com" value={website} onChange={e=>setWebsite(e.target.value)}/></label>{formError&&<p className="error" role="alert">{formError}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Add competitor'}</button></form></Modal>
 </>;
}
