'use client';
import {useEffect,useId,useLayoutEffect,useRef,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {Info,X} from 'lucide-react';

// Product guidance follows the implemented calculations and reporting boundaries.
const help = {
 overview:['Performance','A view of acquisition, paid results, and customer progress for the selected brand.','Start with the summary, find the campaign or channel behind a change, then create an action to investigate or test it.','Live reports, fictional showcases, and imported CSVs are labeled separately. A dash means a value is unavailable, not zero.'],
 period:['Reporting period','The dashboard compares 28 complete reporting days with the preceding 28 days. Recent days are excluded using the reporting buffer.','Check the dates and source timezone before comparing this dashboard with Google. Change the buffer in Goals & tracking if conversions typically arrive later.','This buffer reduces immature reporting; it does not estimate missing conversions.'],
 refresh:['Refreshing reports','Performance loads this brand’s reports when you open it. Refresh performance requests newer reports.','Use Refresh performance before making a decision, then check Sources & coverage for collection times or errors.','Automatic requests use a 15-minute cache; manual requests have a one-minute cooldown. A refresh can use four Zapier reporting actions. Nothing refreshes while the site is closed.'],
 goals:['Goals & tracking','Your business definitions and targets give the dashboard a meaningful point of comparison.','Choose the business model, confirm what an Ads conversion represents, set 28-day targets, and classify campaigns. Map GA4 events to the stages you actually track.','Saved plans are internal planning inputs. They do not change Google Ads budgets or Google Analytics settings.'],
 summary:['Executive summary','A quick read of paid results and the channel contributing the largest absolute session change.','Use this to choose where to investigate first, then inspect the paid scorecard or channel table for the supporting records.','It describes observed changes. It cannot establish the cause or the quality of leads without additional evidence.'],
 importedConversions:['Imported conversions','The conversion count included in the selected daily CSV, under the definition saved with that import.','Check the account and conversion definition before comparing periods. Use the matching source records when creating an experiment.','GA4 converted sessions and Google Ads attributed conversions have different meanings. Do not combine them or assume they represent qualified leads.'],
 results:['Paid results','Conversions attributed by Google Ads in the current reporting period. The label follows the result definition you confirm.','Compare volume with the prior period and your target. Check that primary conversion actions represent the business outcome you intend to measure.','Conversions can be fractional. Mixed conversion actions, calls, clicks, or form submissions are not automatically qualified leads or sales.'],
 cpa:['Cost per result','Google Ads spend divided by its attributed conversions for the same period.','Compare with your cost target and the previous period. Open a campaign to investigate high costs or a potential scaling opportunity.','A zero conversion denominator makes this unavailable. A low cost is useful only when conversion quality is acceptable.'],
 revenue:['Recorded website revenue','Revenue recorded in the GA4 report, using the property’s reporting currency.','Compare with the prior period and your revenue target, then confirm that revenue events and values are being collected correctly.','This is not pipeline, profit, or necessarily revenue attributed to ads. A reported zero can reflect missing tracking; refunds can produce negative values.'],
 demand:['Demand & acquisition','Shows where new users and visits are coming from, and whether those visits lead to engagement or key events.','Look at the daily trend first, then compare channels to find which changes are driving the overall movement.','First-user acquisition and session channels answer different questions and should not be treated as interchangeable.'],
 newUsers:['New users','Users identified as new by GA4, grouped by their first-user acquisition channel.','Use this to assess which channels bring new people to the brand, rather than only bringing existing visitors back.','Tracking consent, device changes, and identification settings affect who GA4 can recognize as new.'],
 sessions:['Sessions','Visits recorded by GA4. One person can have multiple sessions.','Compare volume across periods and channels, then check engagement and meaningful events to judge the traffic’s usefulness.','Sessions are not unique people, leads, or customers.'],
 engaged:['Engaged sessions','Sessions that GA4 classifies as engaged under the property’s engagement settings.','Compare this trend with sessions to see whether growth in visits is accompanied by growth in engaged activity.','Engagement is a behavioral signal, not proof of purchase intent or lead quality.'],
 engagement:['Engagement rate','Engaged sessions divided by all sessions within the same channel and reporting period.','Use it alongside volume and key events to spot channels that bring traffic with limited engagement.','Compare like-for-like tracking and definitions; a higher rate alone does not prove higher revenue.'],
 keyEvents:['Key events','Occurrences of events marked as important in Google Analytics.','Check which events your property marks as key events, then use the count to understand meaningful activity by channel.','Events can repeat and one person can trigger several. Counts are not unique leads, customers, or a session conversion rate.'],
 trend:['Daily trend','Daily values for the current and preceding 28-day periods, aligned by day in each window.','Choose sessions, engaged sessions, or new users. Look for sustained shifts or unusual days, then inspect daily values for exact dates and amounts.','Aligned points are different calendar dates. Investigate campaigns, tracking changes, and seasonality before assigning a cause.'],
 acquisition:['Where new people discover you','Ranks first-user acquisition channels by the number of new users they introduce.','Use this to understand discovery and top-of-funnel reach. Compare it with session-channel engagement to see what happens after discovery.'],
 channels:['Where visits become engagement','Groups sessions, engagement, and key events by the channel associated with a visit.','Look for channels that combine useful traffic volume with engagement and key events. Follow up on large changes rather than treating volume alone as success.'],
 change:['Period change','The relative difference between the current value and the preceding comparison period.','Use the percentage together with the underlying volume. A large percentage can come from a small baseline.','A zero or missing comparison baseline cannot produce a meaningful relative percentage.'],
 paid:['Paid programs','A campaign scorecard combining spend, recorded results, your targets, and rules-based assessment prompts.','Classify program types, enter campaign plans, then open a campaign to inspect the reason behind its assessment and create an action.','These are review prompts. GrowthOS does not change campaigns or budgets.'],
 program:['Program types & objectives','Your classifications distinguish branded search, non-brand search, prospecting, and retargeting. Objectives describe each campaign’s job.','Set these in Goals & tracking, then filter the scorecard to compare programs serving a similar purpose.','Unclassified means no classification has been saved. Labels are supplied by you, not inferred from campaign names.'],
 spend:['Spend & period plan','Recorded Google Ads spend, shown against the 28-day spending plan you entered for the campaign.','Use the plan percentage to review how much of the period allowance has been used. Compare spend with results and cost per result.','This is not Google’s live daily budget or a forecast of end-of-period spend.'],
 assessment:['Campaign assessments','Rules-based prompts use spend, conversion volume, result verification, cost targets, and report freshness.','Select View reason to understand the assessment. Investigate tracking and conversion quality before deciding to scale, hold, or change a program.','Scaling prompts require at least 10 conversions, verified results, and a cost target. Insufficient evidence means the app cannot support a strong assessment.'],
 impressions:['Impressions','The number of times an ad or search result was shown in the selected source.','Use with clicks and click-through rate to distinguish visibility from the ability to attract visits.','Repeated views count; impressions are not unique reach.'],
 clicks:['Clicks','Clicks recorded by the selected advertising or search source.','Compare with impressions to assess response, then with website activity and conversions to examine what happens after the click.','Clicks and GA4 sessions use different measurement systems and may not match.'],
 ctr:['Click-through rate','Clicks divided by impressions for the same source and period.','Use it to investigate ad relevance or search-result appeal, while accounting for position, audience, and intent.','A higher click-through rate does not necessarily mean better conversion quality or return.'],
 cpc:['Cost per click','Google Ads spend divided by clicks for the same campaign and period.','Use it to understand traffic cost, alongside conversion rate and cost per result.','Cheaper clicks can still be poor value if they do not produce useful outcomes.'],
 conversionValue:['Ads conversion value','The value assigned to conversions under the Google Ads account’s settings.','Check whether the values reflect actual transaction revenue or assigned lead values before using them for return calculations.','Conversion value is not automatically sales revenue or profit.'],
 funnel:['Brand funnel','Shows activity or linked progression through the stages chosen for this brand’s business model.','Choose GA4 milestones for tracking activity, or Linked journeys to follow the same anonymized entities through ordered stages. Investigate where progression appears weak.','Aggregate GA4 events do not establish a same-person funnel. Linked cohorts can have different amounts of time to convert.'],
 funnelEvidence:['Funnel evidence','GA4 milestones count separately tracked events. Linked journeys use dates for the same anonymized person or account.','Choose the evidence that matches the question: “Did this event happen?” or “Did these same entities advance?”','Never divide unrelated event totals and call the result a true step-to-step conversion rate.'],
 stage:['Funnel stage','A milestone in the selected business model, using the evidence mode shown above the funnel.','In GA4 mode, map the event that genuinely represents this milestone in Goals & tracking. In Linked journeys mode, provide its reached date for each entity.','A missing mapping means the stage is unmeasured. A click on a call button is not a verified call, qualified lead, or booked job.'],
 journeys:['Journey CSV','One row per anonymized person or account, with ordered dates for up to five funnel stages.','Download the headers. Fill entity_id and stage_1_at through stage_5_at with YYYY-MM-DD dates; leave unreached later stages blank. Include both periods.','Do not include names or contact details. Aggregate GA4 landing-page exports cannot substitute for linked journeys.'],
 coverage:['Sources & coverage','Identifies the report, account, timezone, date coverage, collection time, and known reporting limitations.','Open this before acting on an unexpected value. Confirm the account and dates, check freshness, and download the report if you need to inspect the underlying rows.','Missing values or incomplete reports are different from verified zero activity.'],
 csv:['Imported CSV reports','A separate inventory of imported daily reports and GA4 landing-page summaries.','Choose the source and account to inspect records. Import daily rows for trend comparisons or action measurement; use a summary for its reported date range.','CSV records do not replace the connected reports above. Do not add overlapping summaries or distinct report grains together.'],
 landing:['Landing-page summary','The exported GA4 totals for each landing page across one selected date range.','Use this to compare entry pages and spot pages that deserve investigation. Select a report period to inspect its original export.','It has no daily trend. Key events can repeat, and user counts should not be summed across pages.'],
 sessionRate:['Session key event rate','The exported proportion of sessions in which at least one key event occurred.','Use it alongside session volume to compare how often visits include a key event. Confirm the event definition first.','This is the exported rate, not key-event count divided by sessions; multiple key events can occur in one session.'],
 activeUsers:['Active users','The GA4 active-user count in the exported report for the page and period.','Use it as a view of the audience using each entry page, alongside sessions and new users.','A person can appear under multiple pages. Adding page-level user counts does not produce a deduplicated audience total.'],
 engagementTime:['Average engagement time','The engagement duration, in seconds, exported by the GA4 report.','Use it alongside session volume, key events, and page purpose to investigate whether visitors are engaging with the landing page.','Preserve the definition of the original export. It is not automatically the duration of a full visit.'],
 actions:['Actions & experiments','Turns a finding into assigned work, an implementation record, and a saved outcome review.','Create an action from a campaign assessment or Today opportunity, or start one here. Use a task for a piece of work and an experiment for a measurable change.','Actions belong to the selected brand. Assigning a name does not send a notification or grant access.'],
 actionStatus:['Action status','Planned is queued work; In progress is work started; Measuring is an implemented experiment; Completed has a saved completion or review.','Use the counts or Show actions filter to find the work needing attention. Completed and cancelled actions remain available under All actions.'],
 ownership:['Ownership & timing','An owner records responsibility and an optional due date records when you want the work done.','Use a teammate’s name or team and a realistic date. Update assignment from the action details as plans change.','Due dates are separate from measurement windows and do not send reminders.'],
 measurePlan:['Experiment success measure','Fixes the source, metric, direction, improvement target, and before/after window for an experiment.','Choose one primary metric tied to the expected change. A 10% relative improvement from a 5% rate means 5.5%, not 15%.','The source and measurement plan stay fixed. Sample and live data cannot be combined, and rates with zero denominators cannot be compared.'],
 implementation:['Record the implementation','Records what you actually changed and the date it took effect.','Make the change in the source tool first, then describe the destination and exact edit here. A task completes; an experiment moves to Measuring.','The implementation day is excluded from before/after comparison. Recording a change here does not edit an external tool.'],
 beforeAfter:['Before & after','Compares equal 7-, 14-, or 28-day windows immediately before and after implementation, excluding the implementation day.','Refresh Performance or import the matching daily history, then select Check results from loaded data after the reporting buffer has elapsed.','The baseline remains fixed once captured. Checks are manual. Observed movement does not prove causation or statistical significance.'],
 review:['Outcome review','Saves your decision and learning alongside the experiment’s evidence and observed result.','Choose Keep, Iterate, Revert, or Inconclusive, and explain what you learned and what else might explain the change.','Keep, Iterate, and Revert require a saved comparison. Revert records your decision; you must make any reversal in the source tool yourself.'],
 model:['Business model & event mapping','The business model selects the stage labels for services, software, or ecommerce. Event mappings tell the app which GA4 events represent each milestone.','Choose the closest model, refresh reports to discover event names, and map only events that truly represent the stage.','Changing the model clears the event mappings. Offline outcomes need their own records; the app cannot infer them from website clicks.'],
 targets:['Targets & campaign plans','Targets are your chosen 28-day result, cost, and revenue goals. Campaign plans add an objective, segment, spending plan, and optional campaign cost target.','Set realistic goals using comparable historical performance. Review campaign targets separately when programs serve different jobs.','These are planning values, not predictions or external budget changes.'],
 legacy:['Recorded implementation notes','Earlier implementation records contain a change note and the baseline recorded at that time.','Use them as history. For ownership, measurement windows, and a structured outcome review, create an action in Actions & experiments.','Older notes do not automatically become experiments or trigger follow-up checks.'],
} as const;
export type HelpTopic=keyof typeof help;
export default function PerformanceHelp({topic,title}:{topic:HelpTopic;title?:string}){
 const [open,setOpen]=useState(false),[hovered,setHovered]=useState(false);
 const trigger=useRef<HTMLButtonElement>(null),tooltip=useRef<HTMLDivElement>(null);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const tooltipId=useId();const content:readonly string[]=help[topic];const heading=title??content[0];
 const clearTimer=()=>{if(timer.current)clearTimeout(timer.current);timer.current=null;};
 const show=()=>{clearTimer();if(!open)setHovered(true);};
 const leave=()=>{clearTimer();timer.current=setTimeout(()=>setHovered(false),180);};
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 useLayoutEffect(()=>{
  if(!hovered||open||!tooltip.current||!trigger.current)return;
  const tip=tooltip.current,anchor=trigger.current;
  // Native popovers escape card clipping and modal transforms without moving focus.
  tip.showPopover();
  const rect=anchor.getBoundingClientRect(),size=tip.getBoundingClientRect();
  const below=window.innerHeight-rect.bottom-12,above=rect.top-12;
  const placeBelow=below>=size.height||below>=above;
  tip.style.maxHeight=Math.max(80,placeBelow?below:above)+'px';
  const height=tip.getBoundingClientRect().height;
  tip.style.left=Math.max(12,Math.min(rect.left,window.innerWidth-size.width-12))+'px';
  tip.style.top=Math.max(12,placeBelow?rect.bottom+8:rect.top-height-8)+'px';
  const dismiss=()=>setHovered(false);
  const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();dismiss();}};
  window.addEventListener('keydown',escape,true);
  window.addEventListener('resize',dismiss);
  const scroll=(event:Event)=>{if(!tip.contains(event.target as Node))dismiss();};
  window.addEventListener('scroll',scroll,true);
  return()=>{if(tip.isConnected)tip.hidePopover();window.removeEventListener('keydown',escape,true);window.removeEventListener('resize',dismiss);window.removeEventListener('scroll',scroll,true);};
 },[hovered,open]);
 return <Dialog.Root open={open} onOpenChange={setOpen}>
  <Dialog.Trigger asChild><button ref={trigger} type="button" className="performance-info" aria-label={'About '+heading} aria-describedby={hovered&&!open?tooltipId:undefined}
   onPointerEnter={e=>{if(e.pointerType!=='touch')show();}} onPointerLeave={leave}
   onFocus={e=>{if(e.currentTarget.matches(':focus-visible'))show();}} onBlur={()=>{clearTimer();setHovered(false);}}
   onClick={e=>{e.preventDefault();e.stopPropagation();clearTimer();setHovered(false);setOpen(true);}}><Info size={16} aria-hidden="true"/></button></Dialog.Trigger>
  {hovered&&!open&&<div ref={tooltip} id={tooltipId} role="tooltip" popover="manual" className="performance-help-tooltip" onPointerEnter={show} onPointerLeave={leave} onClick={e=>e.stopPropagation()}>
   <strong className="performance-help-title">{heading}</strong><p>{content[1]}</p><strong>How to use it</strong><p>{content[2]}</p>{content[3]&&<div className="performance-help-caveat"><strong>Keep in mind</strong><p>{content[3]}</p></div>}
  </div>}
  <Dialog.Portal><Dialog.Overlay className="modal-overlay performance-help-overlay"/><Dialog.Content className="modal performance-help-dialog" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><Dialog.Title>{heading}</Dialog.Title></div><Dialog.Close className="icon-button" aria-label="Close explanation"><X size={19}/></Dialog.Close></div><Dialog.Description className="performance-help-meaning">{content[1]}</Dialog.Description><h3>How to use it</h3><p>{content[2]}</p>{content[3]&&<div className="notice"><strong>Keep in mind</strong><p>{content[3]}</p></div>}</Dialog.Content></Dialog.Portal>
 </Dialog.Root>;
}
