'use client';
import {useEffect,useState,type FormEvent} from 'react';
export type CompanyAccess={email:string;role:'owner'|'admin'|'member';canAdmin:boolean;companyId:string};
export async function companyRequest(path:string,body?:unknown){const response=await fetch('/api/company/'+path,{cache:'no-store',...(body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('Company workspaces are available on the hosted site.');const data=await response.json();if(!response.ok)throw new Error(data.error??'Company request failed.');return data;}
export default function TeamSettings({access,onOpen}:{access:CompanyAccess|null;onOpen:()=>void}){
 const [members,setMembers]=useState<{email:string;role:string}[]>([]),[activity,setActivity]=useState<{actor:string;action:string;target:string;created_at:string}[]>([]),[email,setEmail]=useState(''),[role,setRole]=useState('member'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function reload(){const data=await companyRequest('team');setMembers(data.members);setActivity(data.activity);}
 useEffect(()=>{if(access?.canAdmin)void reload().catch(e=>setError(e.message));},[access?.canAdmin]);
 async function change(target:string,nextRole:string,remove=false){setBusy(true);setError('');setNotice('');try{await companyRequest('team',{email:target,role:nextRole,remove});await reload();setEmail('');setNotice(remove?'Company access removed.':'Company role saved. The site owner must also grant this person viewer access in the site’s Share settings. No invitation email was sent.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!access)return <div className="panel"><h2>Company team</h2><p>Company access is available to approved accounts on the hosted site.</p></div>;
 return <section className="panel"><div className="section-heading"><h2>Company team</h2><span className="badge">{access.role}</span></div><p>Signed in as {access.email}. Your team can work across company brands. Each brand keeps its reports, imports, drafts, and decisions separate.</p><button className="secondary" onClick={onOpen}>Open current brand</button>{access.canAdmin?<><p className="notice">Add a company role here, then grant the same email <strong>viewer access</strong> using the site’s Share settings. Both are required. An app admin does not need permission to edit the site’s code.</p><form onSubmit={(e:FormEvent)=>{e.preventDefault();void change(email,role);}}><div className="form-grid"><label>Teammate email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Company role<select value={role} onChange={e=>setRole(e.target.value)}><option value="member">Member — reports and recommendations</option><option value="admin">Admin — connections and team access</option></select></label></div><button className="primary" disabled={busy}>Save company role</button></form>{error&&<div className="error" role="alert">{error}</div>}{notice&&<p className="notice" role="status">{notice}</p>}<div className="table-scroll"><table><thead><tr><th>Email</th><th>Role</th><th>Access</th></tr></thead><tbody>{members.map(m=><tr key={m.email}><td>{m.email}</td><td>{m.role==='owner'||m.email===access.email?m.role:<select aria-label={'Role for '+m.email} value={m.role} disabled={busy} onChange={e=>void change(m.email,e.target.value)}><option value="member">Member</option><option value="admin">Admin</option></select>}</td><td>{m.role==='owner'?'Site owner':m.email===access.email?'Your account':<button className="text-button" disabled={busy} onClick={()=>void change(m.email,m.role,true)}>Remove company access</button>}</td></tr>)}</tbody></table></div><details><summary>Recent team activity</summary>{activity.length?activity.map((a,i)=><p key={i}>{new Date(a.created_at).toLocaleString()} · {a.actor} · {a.action.replaceAll('_',' ')} · {a.target}</p>):<p>No team changes yet.</p>}</details></>:<p className="notice">You can view shared reports and work on recommendations. Ask a company admin to change connections or team access.</p>}</section>;
}
