'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,RefreshCw,CheckCircle2,Clock3,Globe2,Database} from 'lucide-react';
import type {WorkspaceState,Recommendation} from '@/lib/domain/types';
import {analyze} from '@/lib/domain/analysis';
import {defaultPerformance,localRange,kinds,kindLabels,type PerformanceKind} from '@/lib/domain/performance';
import {canShowSamples,makePerformanceSample} from '@/lib/domain/performance-samples';
import {reportHealth,todayPriorities,todayFollowUps,type PerformanceFocus,type PerformanceStatus} from '@/lib/domain/today';
import type {ActionSeed} from '@/lib/domain/actions';
import type {Comparison} from './competitor-comparison';

type Research={entries:{id:string;name:string;website:string;status:string}[];comparison?:Comparison};
type Props={state:WorkspaceState;brandId?:string;onPerformance:(focus:PerformanceFocus)=>void;onConnections:()=>void;onCompetitors:()=>void;onImport:()=>void;onRecommendation:(rec:Recommendation)=>void;onCreateAction:(seed:ActionSeed)=>void};
const date=(value:string)=>new Date(value+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric'});
async function request(url:string,signal:AbortSignal,body?:unknown){
 const response=await fetch(url,{signal,cache:'no-store',...(body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});
 if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('Live reports are available on the hosted company site.');
 const data=await response.json();if(!response.ok&&!('report' in data))throw new Error(data.error||'Could not load reports.');return data;
}
export default function TodayBrief(props:Props){
 const {state,brandId}=props;
 const [status,setStatus]=useState<PerformanceStatus|null>(null),[research,setResearch]=useState<Research|null>(null),[error,setError]=useState(''),[researchError,setResearchError]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(!!brandId);
 const controller=useRef<AbortController|null>(null);
 async function load(force=false){
  controller.current?.abort();const current=new AbortController();controller.current=current;
  const signal=current.signal,base='?brand='+encodeURIComponent(brandId??'');
  setError('');setResearchError('');setBusy('Checking sources');
  // Saved research only: opening Today never starts an AI scan or comparison.
  const saved=brandId?request('/api/competitors/status'+base,signal).then(data=>{if(!signal.aborted)setResearch(data.research);}).catch(e=>{if(!signal.aborted){setResearch(null);setResearchError(e.message);}}):Promise.resolve();
  try{
   if(!brandId){setStatus({configured:false,range:localRange(state.profile.timezone,state.performance?.lagDays??7),reports:{},attempts:{}});return;}
   const initial=await request('/api/performance/status'+base,signal);if(signal.aborted)return;setStatus(initial);setLoading(false);
   if(initial.configured)for(const kind of kinds){
    if(signal.aborted)break;setBusy(kindLabels[kind]);
    try{const data=await request('/api/performance/sync'+base,signal,{kind,force});if(!signal.aborted)setStatus(s=>s?{...s,range:data.range,reports:{...s.reports,[kind]:data.report},attempts:{...s.attempts,[kind]:data.attempt}}:s);}
    catch(e){if(!signal.aborted)setStatus(s=>s?{...s,attempts:{...s.attempts,[kind]:{at:new Date().toISOString(),error:(e as Error).message}}}:s);}
   }
  }catch(e){if(!signal.aborted)setError((e as Error).message);}
  finally{await saved;if(!signal.aborted){setLoading(false);setBusy('');}}
 }
 useEffect(()=>{void load();return ()=>controller.current?.abort();},[brandId,state.id]);
 return <TodayContent {...props} status={status} research={research} error={error} researchError={researchError} loading={loading} busy={busy} onRefresh={()=>void load(true)}/>;
}

export function TodayContent({state,status,research,error,researchError,loading,busy,onRefresh,onPerformance,onConnections,onCompetitors,onImport,onRecommendation,onCreateAction}:Props&{status:PerformanceStatus|null;research:Research|null;error:string;researchError:string;loading:boolean;busy:string;onRefresh:()=>void}){
 const baseConfig=state.performance??defaultPerformance(state.profile),sampleMode=canShowSamples(state.profile,status),sampleRange=localRange(state.profile.timezone,baseConfig.lagDays);
 const sample=useMemo(()=>sampleMode?makePerformanceSample(state.profile,sampleRange):null,[sampleMode,state.profile.name,state.profile.website,sampleRange.end,sampleRange.lagDays,sampleRange.timezone]);
 const cfg=sample?{...sample.config,...state.performance,adsResultsVerified:true}:baseConfig,range=sample?sampleRange:status?.range??sampleRange,reports=sample?.reports??status?.reports??{},attempts=sample?{}:status?.attempts??{};
 const priorities=error?[]:todayPriorities(state,reports,range,cfg,attempts),followUps=todayFollowUps(state,error?{}:reports,!!sample,attempts),ready=kinds.filter(k=>reportHealth(reports[k],range,attempts[k]?.error).ready),open=state.recommendations.filter(r=>r.status==='open'),limitations=analyze(state).limitations;
 const report=research?.comparison?.report,confirmed=research?.entries.filter(e=>e.status==='confirmed')??[];
 const stale=report&&(Object.entries(report.targets.brand).some(([key,value])=>String(state.profile[key as keyof typeof state.profile]??'').trim().replace(/\/$/,'')!==value.replace(/\/$/,''))||report.targets.competitors.some(c=>!confirmed.some(e=>e.id===c.id&&e.name===c.name&&e.website===c.website)));
 const period=date(range.start)+' – '+date(range.end),previous=date(range.previousStart)+' – '+date(range.previousEnd);
 return <div className="today-brief">
  <div className="page-heading"><div><div className="eyebrow">{state.profile.name} / DAILY BRIEF</div><h1>What needs your attention.</h1><p>Your next move, the evidence behind it, and the work to follow through.</p></div><button className="secondary" onClick={onRefresh} disabled={!!busy}><RefreshCw size={16} className={busy?'spin':''}/>{busy?'Refreshing…':'Refresh brief'}</button></div>
  <div className="today-orientation"><div><strong>Start with one priority.</strong><span>Review the evidence, decide on a change, then track it in Actions & experiments.</span></div><button className="text-button" onClick={()=>onPerformance({section:'actions'})}>Open your action board <ArrowRight size={15}/></button></div>
  {sample&&<p className="notice"><strong>SAMPLE DATA · Fictional brand showcase.</strong> These priorities demonstrate the workflow. They are not actual business results.</p>}
  <div className="today-period"><span><strong>{period}</strong> vs {previous} · {range.timezone}</span><span>28 complete days · {range.lagDays}-day reporting buffer</span></div>
  <p className="subtle today-period-explanation">“Today” is your work list. Performance findings use the latest complete reporting periods above, not today’s unfinished numbers.</p>
  {error&&<div className="error" role="alert">{error} Priorities are paused until reports can be checked.</div>}
  <details className="today-sources"><summary><Database size={15}/>{loading?'Checking report coverage…':sample?'4 sample reports available':`${ready.length} of 4 daily reports ready`}<span>{busy?`Updating ${busy.toLowerCase()}…`:'Sources & freshness'}</span></summary><div className="today-source-grid">{kinds.map(kind=>{const r=reports[kind],health=reportHealth(r,range,attempts[kind]?.error);return <div key={kind}><strong>{kind==='paid'?'Google Ads':'GA4'} · {kindLabels[kind]}</strong><span className={'badge '+(!health.ready?'today-warning':'')}>{health.label}</span><p>{health.detail}</p>{r&&<small>{r.provider} · {r.account.name}<br/>{r.account.timezone} · {r.account.currency}<br/>Report: {r.start} – {r.end}<br/>Collected {new Date(r.collectedAt).toLocaleString()}</small>}{!!r?.limitations.length&&<p>{r.limitations.join(' ')}</p>}</div>;})}</div><p className="subtle">Reports refresh on open, sharing Performance’s 15-minute cache. Manual refresh has a one-minute cooldown. A full refresh can use four Zapier reporting actions. Saved website research is only reloaded here.</p><button className="text-button" onClick={onConnections}>Manage this brand’s connections <ArrowRight size={14}/></button></details>
  {!loading&&!error&&!sample&&ready.length<4&&<div className="notice today-setup"><div><strong>{status?.configured?'Some reports need attention.':'Connect reports to build your brief.'}</strong><p>{status?.configured?'Available reports can still produce priorities. Missing, outdated or failed reports are excluded; check Sources & freshness above.':'Connect this brand’s GA4 and Google Ads reporting actions, then confirm the business result and cost target in Performance.'}</p></div><button className="secondary" onClick={onConnections}>Review connections <ArrowRight size={15}/></button></div>}
  <section aria-labelledby="today-priorities"><div className="section-heading"><div><span className="eyebrow">01 / DECIDE WHAT TO DO</span><h2 id="today-priorities">Your top priorities</h2><p>Measurement first, then campaign efficiency and meaningful traffic changes.</p></div><button className="text-button" onClick={()=>onPerformance({section:'paid'})}>View Performance <ArrowRight size={15}/></button></div>
   {loading?<div className="panel" role="status">Loading this brand’s reports…</div>:priorities.length?<div className="today-priority-grid">{priorities.slice(0,3).map((p,i)=><article className="panel today-priority" key={p.id}><div className="today-priority-top"><span className="today-rank">0{i+1}</span><span className="badge">{sample?'Sample · ':''}{p.focus.section==='goals'?'Measurement':'Review suggested'}</span></div><h3>{p.title}</h3><p className="today-evidence">{p.observed}</p><dl><dt>Why it matters</dt><dd>{p.why}</dd><dt>Your next step</dt><dd>{p.next}</dd></dl><small>{p.source} · {period}</small><button className="primary" onClick={()=>onPerformance(p.focus)}>{p.label} <ArrowRight size={15}/></button></article>)}</div>:<div className="panel today-empty"><CheckCircle2 size={24}/><div><h3>{error?'Your priorities need fresh evidence.':ready.includes('paid')||ready.includes('traffic')?'No priority flags in the available reports.':'Your first priority is a reliable baseline.'}</h3><p>{error?'Retry the refresh or review the connection before making decisions.':ready.includes('paid')||ready.includes('traffic')?'These checks look for spend without conversions, cost-target gaps, efficient campaigns and substantial traffic declines. This is not an all-clear for the business; review coverage, goals and tracked work.':'Load daily reports for this brand, then define what a valuable result means. CSV findings and saved actions remain available below.'}</p><button className="text-button" onClick={()=>onPerformance({section:'goals'})}>Review goals & tracking <ArrowRight size={15}/></button></div></div>}
   {priorities.length>3&&<p className="subtle">Showing the three highest-ranked priorities. Review other campaign assessments in Performance.</p>}
  </section>
  <div className="today-secondary-grid">
   <section className="panel" aria-labelledby="today-followup"><div className="section-heading"><div><span className="eyebrow">02 / FOLLOW THROUGH</span><h2 id="today-followup">Work to follow up on</h2></div><Clock3 size={21}/></div><p>Due work and experiments that need your review.</p>{followUps.length?<div className="today-followups">{followUps.slice(0,4).map(item=><button className="today-followup" key={item.plan.id} onClick={()=>onPerformance({section:'actions',actionId:item.plan.id})}><span className="badge">{item.label}{item.plan.source?.origin==='sample'?' · Sample':''}</span><strong>{item.plan.title}</strong><span>{item.detail}</span><small>Open {item.plan.kind} <ArrowRight size={13}/></small></button>)}</div>:<div className="today-quiet"><h3>No active actions yet.</h3><p>Choose a finding and create an action with an owner and a due date. For experiments, record the change and measure what happened afterward.</p></div>}<button className="text-button" onClick={()=>onPerformance({section:'actions'})}>View all actions & experiments <ArrowRight size={15}/></button></section>
   <section className="panel" aria-labelledby="today-ideas"><div className="section-heading"><div><span className="eyebrow">03 / FIND YOUR NEXT TEST</span><h2 id="today-ideas">Ideas from competitors</h2></div><Globe2 size={21}/></div>{researchError?<p className="notice">Saved research could not be loaded. {researchError}</p>:stale?<p className="notice">Your brand profile or competitors changed after the saved comparison. Update it before using these ideas.</p>:report?.opportunities.length?<><p className="subtle">Saved website research · {new Date(report.completedAt).toLocaleDateString()}<br/>AI-generated hypotheses to test; not evidence of competitor sales.</p>{report.opportunities.slice(0,2).map((idea,i)=><article className="today-idea" key={i}><h3>{idea.title}</h3><p>{idea.change}</p><details><summary>Why this test & how to measure it</summary><p>{idea.rationale}</p><p>{idea.measurement}</p><div className="comparison-sources">{idea.evidence.map(link=><a href={link.url} key={link.url} target="_blank" rel="noopener noreferrer">{link.title}</a>)}</div></details><button className="text-button" disabled={state.mode==='cloud'} onClick={()=>onCreateAction({title:idea.title,summary:idea.rationale+'\nChange to test: '+idea.change+'\nMeasure: '+idea.measurement,reference:'Website comparison · '+report.completedAt+' · '+idea.evidence.map(e=>e.url).join(' · ')})}>Plan this test <ArrowRight size={14}/></button></article>)}</>:<div className="today-quiet"><h3>{report?'No source-backed ideas in this comparison.':'Bring a competitor insight into your plan.'}</h3><p>Confirm competitors, then compare their websites with yours for offers, trust, messaging and conversion ideas.</p></div>}<button className="text-button" onClick={onCompetitors}>{report?'Open saved comparison':'Go to Competitors'} <ArrowRight size={15}/></button><p className="subtle">Opening this brief does not run a new scan.</p></section>
  </div>
  <details className="panel today-csv"><summary>From your {state.mode==='demo'?'sample CSV data':'CSV imports'} · {open.length} open findings</summary><p>File-based findings use their own report dates and thresholds. They are separate from the connected reports above.</p>{state.recommendations.length?<div className="today-csv-list">{state.recommendations.map(rec=><button key={rec.id} onClick={()=>onRecommendation(rec)}><span><small>{rec.source.toUpperCase()} · {rec.status} · {state.mode==='demo'?'SAMPLE':'CSV'}</small><strong>{rec.title}</strong></span><ArrowRight size={16}/></button>)}</div>:<p>No saved CSV findings for this brand.</p>}{!!limitations.length&&<details><summary>CSV coverage checks</summary>{limitations.map((message,i)=><p key={i}>{message}</p>)}</details>}<button className="text-button" onClick={onImport}>Import a CSV report <ArrowRight size={15}/></button></details>
 </div>;
}
