'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {RefreshCw,Link2} from 'lucide-react';
type Source='ga4'|'ads';
type Report={source:Source;account:{id:string;name:string;currency:string;timezone:string};start:string;end:string;collectedAt:string;columns:string[];rows:string[][];rateColumn?:number;limitations:string[]};
type Attempt={at:string;error?:string|null};
type Status={configured:boolean;canAdmin:boolean;settings:{propertyName?:string;propertyId?:string;customerId?:string;managerId?:string;accountId?:string};reports:Partial<Record<Source,Report|null>>;attempts:Partial<Record<Source,Attempt|null>>};
async function zapierRequest(path:string,body?:unknown,brandId?:string){const response=await fetch('/api/zapier/'+path+'?brand='+encodeURIComponent(brandId??''),{cache:'no-store',...(body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('Live reports are available on the hosted workbench.');const data=await response.json();if(!response.ok&&!Object.hasOwn(data,'report'))throw new Error(data.error??'Could not load live reports.');return data;}
export default function ZapierReports({page,onConnections,brandId}:{page:string;onConnections:()=>void;brandId?:string}){
 const api=(path:string,body?:unknown)=>zapierRequest(path,body,brandId);
 const [accountSettings,setAccountSettings]=useState<Status['settings']>({});
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[token,setToken]=useState(''),[saving,setSaving]=useState(false),[busy,setBusy]=useState(false);const refreshing=useRef(false);
 async function refresh(force:boolean){if(refreshing.current)return;refreshing.current=true;setBusy(true);setError('');try{for(const source of ['ga4','ads'] as Source[]){try{const result=await api('sync',{source,force});setStatus(s=>s?{...s,reports:{...s.reports,[source]:result.report},attempts:{...s.attempts,[source]:result.attempt??{at:new Date().toISOString(),error:result.error}}}:s);}catch(e){setStatus(s=>s?{...s,attempts:{...s.attempts,[source]:{at:new Date().toISOString(),error:(e as Error).message}}}:s);}}}finally{refreshing.current=false;setBusy(false);}}
 useEffect(()=>{let active=true;api('status').then(s=>{if(!active)return;setStatus(s);setAccountSettings(s.settings);if(s.configured)void refresh(false);}).catch(e=>{if(active)setError(e.message);});return ()=>{active=false;};},[]);
 async function connect(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{await api('configure',{token,settings:accountSettings});setToken('');const next=await api('status');setStatus(next);await refresh(true);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 if(!['Today','Performance','Connections'].includes(page))return null;
 if(!status&&!error)return <p id="zapier-reports" tabIndex={-1} className="subtle" role="status">Loading live report status…</p>;
 if(!status)return page==='Connections'?<div id="zapier-reports" tabIndex={-1} className="notice">{error}</div>:null;
 const expanded=page==='Connections'||page==='Performance';
 return <section id="zapier-reports" tabIndex={-1} className="panel zapier-reports" aria-label="Live reports via Zapier"><div className="section-heading"><div><span className="eyebrow">YOUR CONNECTED ACCOUNTS</span><h2>Live Google reports</h2></div>{status.configured?<button className="secondary" disabled={busy} onClick={()=>void refresh(true)}><RefreshCw size={16}/>{busy?'Refreshing…':'Refresh now'}</button>:<span className="badge">Website setup needed</span>}</div><p className="subtle">{status.configured?'Updates when you open the site. Automatic checks reuse reports collected within 15 minutes; manual refresh is limited to once per minute.':'Your Zapier connections need a separate connection token for this website.'}</p>{error&&<div role="alert" className="error">{error}</div>}
 {!status.configured&&page!=='Connections'&&<button className="secondary" onClick={onConnections}><Link2 size={16}/>Set up website updates</button>}
 {page==='Connections'&&status.canAdmin&&<details open={!status.configured}><summary>{status.configured?'Update Zapier connection token':'Connect the website to Zapier'}</summary><p>This brand reads reports for <strong>{status.settings.propertyName||'the property you choose below'}</strong> and Google Ads account <strong>{status.settings.customerId||'not set yet'}</strong>.</p><ol><li>Open <a href="https://mcp.zapier.com" target="_blank" rel="noreferrer">Zapier MCP</a> and add a separate server for <strong>Other</strong>, named Subgrowth Website.</li><li>In that server’s <strong>Settings</strong>, select <strong>Agentic mode</strong> and save changes. This website requires Agentic mode.</li><li>Enable Google Analytics 4 “Run Report for a Property” and Google Ads “API Request” (“Make API Mutating Request”). The website uses this action only to read campaign reports. Select your existing Google account as each app’s default connection.</li><li>In that server’s <strong>Connect</strong> tab, generate a connection token and paste only the token below.</li></ol><form onSubmit={connect}><p>Use the account IDs for this brand only. Use a dedicated Zapier server for each brand.</p><div className="form-grid">{([['propertyName','GA4 property name','Brand website'],['accountId','GA4 account ID','accounts/123456789'],['propertyId','GA4 property ID','properties/123456789'],['customerId','Google Ads customer ID','10 digits, no dashes'],['managerId','Google Ads manager ID','10 digits, no dashes']] as const).map(([field,label,placeholder])=><label key={field}>{label}<input required maxLength={200} value={accountSettings[field]??''} placeholder={placeholder} onChange={e=>setAccountSettings(v=>({...v,[field]:e.target.value}))}/></label>)}</div><label>Zapier connection token<input type="password" autoComplete="off" spellCheck={false} required minLength={20} maxLength={4096} value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste token securely"/></label><p className="subtle">Encrypted storage for this brand. Teammates can view reports; only admins can manage this connection. The saved token is never returned to the browser. Report requests use Zapier tasks under your plan.</p><button className="primary" disabled={saving||busy}>{saving?'Connecting…':'Save token & load reports'}</button></form></details>}
 {!status.canAdmin&&!status.configured&&<p className="notice">Ask a company admin to connect Zapier.</p>}{status.configured&&page==='Connections'&&status.canAdmin&&<details><summary>Disconnect Zapier</summary><p>This removes this brand’s saved token and live reports. You can reconnect later. Revoke the token in Zapier to disable it there too.</p><button className="secondary" disabled={busy||saving} onClick={async()=>{setSaving(true);try{await api('disconnect',{});setStatus(await api('status'));}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>Remove connection and live reports</button></details>}{status.configured&&(['ga4','ads'] as Source[]).map(source=>{const report=status.reports[source],attempt=status.attempts[source];return <article className="live-connection" key={source}><div className="section-heading"><h3>{source==='ga4'?'Google Analytics 4':'Google Ads'}</h3><span className="badge">{attempt?.error?'Needs attention':report?'Report loaded':busy?'Loading…':'Awaiting first report'}</span></div>{attempt?.error&&<div className="error" role="alert">{attempt.error}{report&&' Showing the last successful report below.'}</div>}{report?<><p><strong>{report.account.name}</strong> · {report.start} – {report.end}</p><p className="subtle">Last successful update: {new Date(report.collectedAt).toLocaleString()} · {report.rows.length} rows · {report.account.currency} · {report.account.timezone}</p>{expanded&&<><div className="table-scroll ga4-summary-table"><table><thead><tr>{report.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{report.rows.slice(0,200).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{j===report.rateColumn?`${(Number(cell)*100).toFixed(2)}%`:cell}</td>)}</tr>)}</tbody></table></div>{report.rows.length===0&&<p>No records in this reporting period.</p>}{report.rows.length>200&&<p>Showing the first 200 rows.</p>}<ul className="subtle">{report.limitations.map(l=><li key={l}>{l}</li>)}</ul></>}</>:<p className="subtle">No successful report saved yet.</p>}</article>;})}
 {status.configured&&<p className="subtle">Live reports are separate from sample data and CSV-based recommendations. Nothing refreshes while the site is closed.</p>}</section>;
}
