import {load,save,scopes} from './security.mjs';
export async function google(url,token,body,headers={}){
 // All destinations are constructed by server code, never provided by callers.
 for(let attempt=0;attempt<3;attempt++){
  const response=await fetch(url,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,...(body?{'content-type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(25000)});
  if([429,500,502,503,504].includes(response.status)&&attempt<2){await new Promise(r=>setTimeout(r,500*(attempt+1)));continue;}
  const data=await response.json();
  if(!response.ok){const reason=data.error?.details?.flatMap(d=>d.errors??[]).map(e=>e.errorCode?Object.values(e.errorCode).join(', '):'').filter(Boolean).join('; ');const message=data.error?.message??'Google rejected the request.';throw new Error(`Google ${response.status}: ${reason?reason+'. ':''}${message}`);}
  return data;
 }
}
export async function exchange(env,parameters){const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,...parameters}),signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw new Error(data.error==='invalid_grant'?'Google authorization expired or was revoked. Reconnect this source.':'Google could not authorize this connection. Check the client settings and reconnect.');return data;}
export async function accessToken(env,user,source){const connection=await load(env,user,source);if(!connection)throw new Error('Connect this Google source first.');if(connection.expiresAt>Date.now()+60000)return connection.accessToken;const tokens=await exchange(env,{grant_type:'refresh_token',refresh_token:connection.refreshToken});const updated={...connection,accessToken:tokens.access_token,refreshToken:tokens.refresh_token??connection.refreshToken,expiresAt:Date.now()+tokens.expires_in*1000};await save(env,user,source,updated);return updated.accessToken;}
async function adsSearch(token,customer,manager,query){let rows=[],pageToken;do{const data=await google(`https://googleads.googleapis.com/v25/customers/${customer}/googleAds:search`,token,{query,...(pageToken?{pageToken}:{})},manager?{'login-customer-id':manager}:{});rows.push(...(data.results??[]));pageToken=data.nextPageToken;if(rows.length>10000)throw new Error('Report exceeds 10,000 rows. Choose a shorter date range.');}while(pageToken);return rows;}
export async function accounts(source,token){
 if(source==='ga4'){let items=[],pageToken;do{const data=await google(`https://analyticsadmin.googleapis.com/v1beta/accountSummaries?pageSize=200${pageToken?'&pageToken='+encodeURIComponent(pageToken):''}`,token);items.push(...(data.accountSummaries??[]).flatMap(a=>(a.propertySummaries??[]).map(p=>({id:p.property,name:p.displayName,group:a.displayName}))));pageToken=data.nextPageToken;if(items.length>2000)throw new Error('Too many properties to display. Use a Google account with narrower property access.');}while(pageToken);return items;}
 const data=await google('https://googleads.googleapis.com/v25/customers:listAccessibleCustomers',token);const result=[],errors=[];
 if((data.resourceNames??[]).length>50)throw new Error('More than 50 accessible Google Ads accounts. Use a Google account with narrower access.');
 for(const resource of (data.resourceNames??[])){const customer=resource.split('/').at(-1);try{const clients=await adsSearch(token,customer,null,'SELECT customer_client.id, customer_client.descriptive_name, customer_client.currency_code, customer_client.time_zone, customer_client.manager FROM customer_client');for(const row of clients){const c=row.customerClient;if(!c.manager)result.push({id:String(c.id),name:c.descriptiveName||String(c.id),currency:c.currencyCode,timezone:c.timeZone,manager:customer});}}catch(error){errors.push(error.message);}}
 if(errors.length)throw new Error('Account discovery is incomplete. '+errors[0]);
 return [...new Map(result.map(a=>[a.id,a])).values()];
}
export function dates(start,end){if(!/^\d{4}-\d{2}-\d{2}$/.test(start??'')||!/^\d{4}-\d{2}-\d{2}$/.test(end??''))throw new Error('Choose valid report dates.');const a=new Date(start+'T00:00:00Z'),b=new Date(end+'T00:00:00Z');if(!Number.isFinite(+a)||!Number.isFinite(+b)||a.toISOString().slice(0,10)!==start||b.toISOString().slice(0,10)!==end||b<a||b-a>90*86400000||b>Date.now())throw new Error('Choose a valid date range of at most 90 days, ending today or earlier.');}
export async function report(source,token,account,start,end){dates(start,end);
 if(source==='ga4'){
  if(!/^properties\/\d+$/.test(account.id))throw new Error('Choose a GA4 property.');
  const property=await google(`https://analyticsadmin.googleapis.com/v1beta/${account.id}`,token);
  const metrics=['sessions','keyEvents','sessionKeyEventRate','activeUsers','newUsers','userEngagementDuration','totalRevenue'];
  let rows=[],offset=0,rowCount=0,metadata={},flags=new Set();
  do{const data=await google(`https://analyticsdata.googleapis.com/v1beta/${account.id}:runReport`,token,{dateRanges:[{startDate:start,endDate:end}],dimensions:[{name:'landingPage'}],metrics:metrics.map(name=>({name})),limit:'1000',offset:String(offset),orderBys:[{metric:{metricName:'sessions'},desc:true}]});rowCount=data.rowCount??0;metadata=data.metadata??{};if(metadata.subjectToThresholding)flags.add('Google may withhold data because of reporting thresholds.');if(metadata.dataLossFromOtherRow)flags.add('Some results are grouped into an (other) row.');if(metadata.samplingMetadatas?.length)flags.add('This report contains sampled data.');rows.push(...(data.rows??[]).map(r=>[r.dimensionValues[0].value,...r.metricValues.map(v=>v.value)]));offset+=data.rows?.length??0;if(rowCount>10000)throw new Error('Report exceeds 10,000 rows. Choose a shorter date range.');if(!data.rows?.length&&offset<rowCount)throw new Error('Google returned an incomplete report. Try again.');}while(offset<rowCount);
  return {account:{...account,currency:metadata.currencyCode??property.currencyCode,timezone:property.timeZone},columns:['Landing page','Sessions','Key events','Session key event rate','Active users','New users','Total engagement (seconds)','Total revenue'],rows,rateColumn:3,limitations:[...flags,'Date-range summary; key events are event counts. Session key-event rates are exported directly from GA4.','Recent data can change as Google finishes processing.']};
 }
 if(!/^\d+$/.test(account.id)||account.manager&&!/^\d+$/.test(account.manager))throw new Error('Choose a Google Ads account.');
 const rows=await adsSearch(token,account.id,account.manager,`SELECT campaign.id, campaign.name, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions, metrics.conversions_value FROM campaign WHERE segments.date BETWEEN '${start}' AND '${end}'`);
 return {account,columns:['Campaign','Campaign ID','Impressions','Clicks','Spend','Conversions','Conversion value'],rows:rows.map(r=>[r.campaign.name,r.campaign.id,r.metrics.impressions??'0',r.metrics.clicks??'0',String(Number(r.metrics.costMicros??0)/1e6),r.metrics.conversions??'0',r.metrics.conversionsValue??'0']),limitations:['Conversions follow the account’s primary conversion settings and attribution model; fractional values are preserved.','Recent conversions may arrive later. Confirm conversion lag before changing budgets.']};
}
