import {emptyWorkspace,id,dayOffset,dateInZone,type Metric,type Source} from './types';
import {refreshRecommendations} from './analysis';
import {saveBrand,createDraft} from './workflow';
export function makeDemo(now=new Date()){
 let state=emptyWorkspace('demo');state=saveBrand(state,{...state.profile,name:'Forma',website:'https://example.com',products:'Project management software',audience:'Small creative teams and independent studios',geography:'United States & Canada',goals:'Grow qualified demo requests. Make paid acquisition more efficient.',budget:12000,voice:'Thoughtful, confident, and clear. Practical language, no hype.',approvedClaims:'Project management software for creative teams.',competitors:'Example competitors have not been configured.'});
 const today=dateInZone(now,state.profile.timezone);
 const specs:{source:Source;entity:string;kind:string}[]=[{source:'ads',entity:'Non-brand · Project management',kind:'spend'},{source:'ga4',entity:'/book-a-demo',kind:'conversion'},{source:'gsc',entity:'/guides/creative-project-management',kind:'ctr'},{source:'gsc',entity:'/blog/creative-workflows',kind:'traffic'}];
 for(const spec of specs){const importId=id();const delay=spec.source==='ads'?7:spec.source==='gsc'?3:2;const end=dayOffset(today,-delay);const metrics:Metric[]=[];for(let i=55;i>=0;i--){const recent=i<7;metrics.push({id:id(),importId,source:spec.source,account:'sample-forma',date:dayOffset(end,-i),entity:spec.entity,grain:'date_entity',currency:'USD',timezone:state.profile.timezone,definition:spec.source==='ga4'?'Sessions with demo_request / sessions':spec.source==='ads'?'Account primary conversions; currency units':'Web search, daily page totals',collectedAt:now.toISOString(),sessions:spec.source==='ga4'?200:null,conversions:spec.source==='ga4'?(recent?5:9):spec.source==='ads'?(recent?0:2):null,spend:spec.source==='ads'?(recent?84:70):null,clicks:spec.source==='gsc'?(spec.kind==='ctr'?18:recent?30:60):spec.source==='ads'?50:null,impressions:spec.source==='gsc'?(spec.kind==='ctr'?1800:900):null});}state.metrics.push(...metrics);state.imports.push({id:importId,filename:`SAMPLE-${spec.source}-${spec.kind}.csv`,source:spec.source,account:'sample-forma',fingerprint:importId,createdAt:now.toISOString(),rowCount:metrics.length,status:'imported',start:metrics[0].date,end,currency:'USD',timezone:state.profile.timezone,definition:metrics[0].definition});}
 state=refreshRecommendations(state,now);const rec=state.recommendations.find(r=>r.kind==='conversion');if(rec)state=createDraft(state,rec).state;return state;
}
