import {type WorkspaceState,type Draft,type Recommendation,type RecommendationStatus,type Profile,id,ProfileSchema} from './types';
export function saveBrand(state:WorkspaceState,profile:Profile){const approved=ProfileSchema.parse(profile);return {...state,profile:approved,brandVersions:[...state.brandVersions,{id:id(),version:state.brandVersions.length+1,profile:approved,createdAt:new Date().toISOString(),source:'User approved' as const}]};}
export function createDraft(state:WorkspaceState,rec:Recommendation):{state:WorkspaceState;draft:Draft}{
 const existing=state.drafts.find(d=>d.id===rec.draftId);if(existing)return {state,draft:existing};
 if(!rec.evidenceIds.every(e=>state.metrics.some(m=>m.id===e)))throw new Error('Draft blocked: an evidence reference is missing.');
 const isSEO=rec.kind==='ctr';const isCopy=rec.kind==='conversion';
 const content=isSEO?`TITLE OPTION\n${state.profile.products||'[Product or service]'} | ${state.profile.name}\n\nMETA DESCRIPTION\nExplore ${state.profile.products||'[approved product description]'} for ${state.profile.audience||'[target audience]'}. ${state.profile.conversion}.\n\nREVIEW CHECKLIST\n• Confirm query intent and search position.\n• Verify all wording against approved brand facts.\n• Check title and description length before implementation.`:isCopy?`HEADLINE OPTION\n${state.profile.products||'[Your product]'}, built around your next step.\n\nSUPPORTING COPY\nExplore how ${state.profile.name} serves ${state.profile.audience||'[your target audience]'}.\n\nCTA OPTION\n${state.profile.conversion}\n\nINVESTIGATION\n• Verify conversion tracking before testing copy.\n• Compare traffic source and device mix in GA4.\n• Review the form and mobile conversion path.\n\nReview positioning before use. No performance claim is implied.`:`INVESTIGATION CHECKLIST\n\nObserved: ${rec.summary}\nPeriod: ${rec.start} through ${rec.end}\n\n1. Confirm source coverage and metric definitions.\n2. ${rec.action}\n3. Record findings and choose one reversible experiment.\n4. Capture the implementation date and compare the same metric after ${state.rules.window} complete days.\n\nDo not infer causation from a before/after comparison.`;
 const draft:Draft={id:id(),recommendationId:rec.id,title:isSEO?'A clearer search result':isCopy?'A more focused first impression':'Validate measurement before acting',type:isSEO?'SEO title & description':isCopy?'Landing page copy':'Investigation checklist',objective:rec.action,audience:state.profile.audience,sourceIds:rec.evidenceIds,versions:[{version:1,content,createdAt:new Date().toISOString(),feedback:'Deterministic template from approved profile and source evidence.'}],reviewedVersion:null};
 return {state:{...state,drafts:[draft,...state.drafts],recommendations:state.recommendations.map(r=>r.id===rec.id?{...r,draftId:draft.id}:r)},draft};
}
export function editDraft(state:WorkspaceState,draftId:string,content:string,feedback='Manual edit'):WorkspaceState{const draft=state.drafts.find(d=>d.id===draftId);if(!draft)throw new Error('Draft not found in this workspace.');if(!content.trim()||content.length>30000)throw new Error('Draft must contain 1–30,000 characters.');if(draft.versions.at(-1)?.content===content)return state;return {...state,drafts:state.drafts.map(d=>d.id===draftId?{...d,reviewedVersion:null,versions:[...d.versions,{version:d.versions.length+1,content,feedback,createdAt:new Date().toISOString()}]}:d)};}
export function decide(state:WorkspaceState,recId:string,action:RecommendationStatus,reason:string):WorkspaceState{const rec=state.recommendations.find(r=>r.id===recId);if(!rec)throw new Error('Recommendation not found in this workspace.');if(action==='dismissed'&&!reason.trim())throw new Error('Add a reason so GrowthOS can remember the decision.');return {...state,recommendations:state.recommendations.map(r=>r.id===recId?{...r,status:action}:r),decisions:[{id:id(),recommendationId:recId,action,reason,createdAt:new Date().toISOString(),fingerprint:rec.fingerprint},...state.decisions]};}
export function draftExport(draft:Draft,state:WorkspaceState){const rec=state.recommendations.find(r=>r.id===draft.recommendationId);return `# ${draft.title}\n\n${draft.type} · Version ${draft.versions.length}\nPrepared work — not published\nSource mode: ${state.mode}\n\n## Objective\n${draft.objective}\n\n## Audience\n${draft.audience}\n\n${draft.versions.at(-1)!.content}\n\n## Evidence\n${rec?`${rec.source} / ${rec.account}\n${rec.start} – ${rec.end}\n${rec.summary}`:'No linked recommendation'}\nEvidence IDs: ${draft.sourceIds.join(', ')}\n\n## Review\nTemplate-generated; review wording and factual support before use.\n`;}
